### ISSUE TITLE
IDE Setup Process not working

### ISSUE THREAD

**Issue by sja** [openhab/openhab2#103]
I followed the simple Steps in ide.md to setup my environment. I used a new workspace, switched the target platform but there are still many errors, because there are only ten Plug-ins detected,  all from org.openhab.* but no org.eclipse.smarthome.* or other plugins.

Maven `clean build` from eclipse did not help, either. Just resulted `BUILD SUCCESS`.

I started `mvn clean build` from commandline and got this:

```
ERROR] Internal error: java.lang.RuntimeException: Failed to resolve target definition /Users/sja/Documents/dev/git/homeautomation/openhab2/targetplatform/openhab.target: Failed to load p2 metadata repository from location http://hstaudacher.github.io/osgi-jax-rs-connector: Unable to read repository at http://hstaudacher.github.io/osgi-jax-rs-connector. http://hstaudacher.github.io/osgi-jax-rs-connector is not a valid repository location. -> [Help 1]
```

Is there an old/moved dependency?

Environment:
OS X 10.10.1, Oracle JDK 1.6, 1.7, 1.8 installed.
Maven 3.2.3
Yoxos 5.6

**Comment by kaikreuzer** [comment]
As you can see here, the build should work nicely: https://openhab.ci.cloudbees.com/job/openHAB2/95/consoleFull

Do you have any proxy that prevents access to http://hstaudacher.github.io/osgi-jax-rs-connector?

**Comment by kaikreuzer** [comment]
Hm, ok, I only proved that it worked yesterday - but I just have this build failing as well with the same message: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution/278/console

I will analyze what's wrong with this update site...

**Comment by kaikreuzer** [comment]
I changed the p2 repo url to directly reference version 4.1.1 - it should now work again!

**Comment by sja** [comment]
Looks much better now ;-)
