### ISSUE TITLE
TP definition not correct for org.eclipse.smarthome.core.thing

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#115]
I am no export at this, but the above plugin referenced in the actual TP definition is version 0.8.0.201501151107, which exports ItemChannelLinkRegistry with getBoundItem() missing, although the source code in the master repo on https://github.com/eclipse/smarthome/blob/da77f3d38d31aed03c2153d7afb5235231f05d9d/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java does contain that method?

Is this due to https://github.com/openhab/openhab2/commit/ab84b5cc9f12d71fd99588fb5ab44c811d1aa900 ?

**Comment by kaikreuzer** [comment]
> actual TP definition is version 0.8.0.201501151107
> 
No, I just updated the ESH p2 repo this morning, so it is now 0.8.0.20150120xxxxxx
Please rebuild your target platfom (hint: I usually open the target file in text mode and increase the sequenceNumber by 1 - this makes it update itself quite reliably. And don’t forget to press „Set as Targetplatform“ in the editor in the end).

Regards,
Kai

**Comment by kgoderis** [comment]
The problem persists even with the latest version of the ESH p2 repo.

**Comment by kaikreuzer** [comment]
Ah, I see, you were trying to fool me with your link ;-)
You link points to some old version - if you check what is the current master, you will find this: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java
And indeed, getBoundItem() does not exist anymore. Btw, didn't I tell you that bindings should NOT use the ItemChannelLinkRegistry? :-)
But the good news is: You will now have the functionality that you are looking for right on your ThingHandler: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L232
Hope this helps!

**Comment by kgoderis** [comment]
> On 21 Jan 2015, at 09:21, Kai Kreuzer <notifications@github.com> wrote:
> 
> Ah, I see, you were trying to fool me with your link ;-)
> You link points to some old version - if you check what is the current master, you will find this:
> 
err… well, let’s blame Google then 
> https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java <https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java>
> And indeed, getBoundItem() does not exist anymore. Btw, didn't I tell you that bindings should NOT use the ItemChannelLinkRegistry? :-)
> 

well, you suggested it, but at the time there was no alternative to get the KNX binding working. 

> But the good news is: You will now have the functionality that you are looking for right on your ThingHandler: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L232 <https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L232>

ah.. good news - that will simplify things a bit. I will adjust the code =

**Comment by kgoderis** [comment]
mmh.. bad news. I still need the ItemChannelLinkRegistry in my code. 

in short, for a channel I need to get a list of all linked items (ThingHandler.getLinkedItems thus ok), and then for each of those items, I need to get the list of bound channels, because each of those channels is compared to the channel I did the original lookup of linked items. The ones matching are put on an ignore list to prevent feeding back Command we received to the bus.

a ThingHandler.getLinkedChannels(String item) would be great

**Comment by kaikreuzer** [comment]
I am not sure if I understand your use case. So you when sending an update to an item, you want to make sure that this event does not end up on ANOTHER channel of the same thing that also has a link to the same item? If this is your setup, could you give an example where this happens?

**Comment by kaikreuzer** [comment]
Discussion continued on https://bugs.eclipse.org/bugs/show_bug.cgi?id=458121
