### ISSUE TITLE
http://127.0.0.1:8080/classicui?sitemap=demo not working on fresh install

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#117]
Hi,
Just grabbing latests zip (runtime & demo) from cloudbees, putting it all into a single place, firing up the runtime, and it seems the classic gui can not  be reached at all?

K

**Comment by kgoderis** [comment]
Hue? start_debug.sh does not have -Djetty.home.bundle=org.openhab.io.jetty in the java command line options? I was side blinded by this, I thought the scripts would be exactly the same except for the debug_opts in the debug script. Is this intentional?

**Comment by kaikreuzer** [comment]
Thanks for noticing, this was indeed not intentional!
