### ISSUE TITLE
OpenHab2 Load at Boot

### ISSUE THREAD

**Issue by yeejie** [openhab/openhab2#127]
Hi, I follow the guide for openHAB (1) on http://www.instructables.com/id/OpenHAB-on-Raspberry-Pi/. Then I modify the code of /etc/init.d/openhab to be identical to OpenHab2 Runtime's START.SH. However, the service started but failed afterwards. Below is the snippet of the modified part:

***
ECLIPSEHOME="/opt/openhab2"

cp=$(find $ECLIPSEHOME/runtime/server -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -1);

DAEMON_ARGS="-Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=$HTTPPORT -Djetty.port.ssl=$HTTPSPORT -Djetty.home=$ECLIPSEHOME -Dlogback.configurationFile=$ECLIPSEHOME/runtime/etc/logback.xml -DmdnsName=openhab -Dopenhab.logdir=$ECLIPSEHOME/userdata/logs -Dsmarthome.servicecfg=$ECLIPSEHOME/runtime/etc/services.cfg -Dsmarthome.userdata=$ECLIPSEHOME/userdata -Dorg.quartz.properties=$ECLIPSEHOME/runtime/etc/quartz.properties -Djetty.etc.config.urls=etc/jetty.xml,etc/jetty-ssl.xml,etc/jetty-deployer.xml,etc/jetty-https.xml,etc/jetty-selector.xml -Dfelix.fileinstall.dir=$ECLIPSEHOME/addons -Djava.library.path=$ECLIPSEHOME/lib -Djava.awt.headless=true -jar $cp -console ${TELNETPORT}"

***

Any idea what is wrong and how could I debug? Thanks.﻿

p/s: I got openHAB (1) to boot up properly on the same Raspberry Pi

**Comment by kaikreuzer** [comment]
Do you have any kind of error message or whatsoever?

**Comment by yeejie** [comment]
Hi Kai, sorry to tell that I have no idea how to output the error message
(perhaps you can guide me). I started the service manually inside ssh
terminal (./openhab start). When I check status of OpenHab2 service
(./openhab status) after a minute, it stated Failed (no other message
available).

**Comment by kaikreuzer** [comment]
Sorry, but I do not know this "openhab" script and it is not part of openHAB 2. So you might better want to ask the author of this script on instructables for help?

**Comment by yeejie** [comment]
Alright. My objective is to start openhab2 at boot when running in
Raspberry Pi. Thus when I came across the script, I thought can be used for
openhab2 with little modification. Sorry for posting this irrelevant issue
here.

**Comment by kaikreuzer** [comment]
It is not irrelevant, I just cannot help you with it here ;-)
Maybe just one hint: If openHAB does not startup with any further information, it might be worth to check for log files in the folder runtime/server/configuration. This is where the OSGi framework logs problems if it cannot be started at all.
