### ISSUE TITLE
implement lifecycle behaviour

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#150]
The changes (eclipse/smarthome#212) of the interface "BindingConfigReader" (added methods "startConfigurationUpdate", "stopConfigurationUpdate") implies a change of all classes that implements that interface (e.g. your compat1x bundle).

**Comment by maggu2810** [comment]
Perhaps this could be correct...

<pre>diff --git a/bundles/core/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java b/bundles/core/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
index b93c58b..71629ca 100644
--- a/bundles/core/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
+++ b/bundles/core/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
@@ -54,11 +54,14 @@
 		
 	}
 
-	@Override
-	public void removeConfigurations(String context) {
-		reader.removeConfigurations(context);
-		
-	}
+    @Override
+    public void startConfigurationUpdate(String context) {
+        reader.removeConfigurations(context);
+    }
+
+    @Override
+    public void stopConfigurationUpdate(String context) {
+    }
 
 	private org.openhab.core.items.Item getOpenHABItem(String itemType) throws BindingConfigParseException {
 		return getOpenHABItem(itemType, "itemName");</pre>

**Comment by kaikreuzer** [comment]
I'll adapt it as soon as I release a new stable version of ESH.

**Comment by kaikreuzer** [comment]
This has been addressed with https://github.com/openhab/openhab2/commit/8fce0f997c7e96d260cdb0412d5341af70d66647
