### ISSUE TITLE
Feature request: Lists

### ISSUE THREAD

**Issue by skaggapa** [openhab/openhab2#165]
I would like the possibility to make list items.
Definition could perhaps be something like this?

>String[] playlists "Sonos Playlists" {sonos="playlists"}

If we get lists we could also have the Sonos binding auto fill a playlists list item so that you always get all your sonos playlists in your GUIs.

Im sure there are more use cases for lists. 

Im writing this on openhab2 since this is where I have understood the development happens.

**Comment by kaikreuzer** [comment]
Thanks for your suggestion. Actually, core framework parts are evolving at Eclipse SmartHome (http://github.com/eclipse/smarthome) and not here. But let me answer you anyhow:
I think introducing arrays would have a huge number of impacts all throughout the system. It would need to be defined how to deal with them regarding events, widgets, REST API, persistence etc. I doubt that this is really feasible. What already exists is a "List" widget for the UI - you can actually use a StringItem, define a separator (e.g. ",") and it will happily list you all segments of this item.
