### ISSUE TITLE
Milstones in Github

### ISSUE THREAD

**Issue by SharpNoiZy** [openhab/openhab2#167]
Hi,

just a suggestion, can you maybe use the Milestone feature of Github, so that everyone can see how far away (Measured in issues) the next release is.
I'm really waiting for alpha2, or what ever comes next, but don't want to ask for every release.

Kind regards

**Comment by StephanBieker** [comment]
I sign that.

**Comment by kaikreuzer** [comment]
Fully agree, this is a useful feature. Just created a milestone for alpha 2, which we plan for May 25: https://github.com/openhab/openhab2/milestones
