### ISSUE TITLE
Can not create thing without parameters in Paper UI

### ISSUE THREAD

**Issue by dsalychev** [openhab/openhab2#172]
The repository doesn't contain Paper UI at the moment, but it's a good place to post the issue, I guess.

I tried to create simple openHAB 2.0 binding with help of [this tutorial](http://www.youtube.com/watch?v=30nhm0yIcvA), but found unexpected behavior of Paper UI while creating thing from the binding - it just doesn't create thing without any warnings.

My thing-types.xml doesn't contain any parameters:
```xml
    <thing-type id="gkplatform">
        <label>GadgetKeeper Platform</label>
        <description>Provides connectivity mechanism to the GadgetKeeper Platform.</description>

        <channels>
            <channel id="channel1" typeId="sample-channel"/>
        </channels>        
    </thing-type>

    <channel-type id="sample-channel">
        <item-type>Switch</item-type>
        <label>Enable</label>
        <description>Switches on/off GadgetKeeper connectivity.</description>
    </channel-type>
```
Looking how to solve my problem, I've found this place in `http://localhost:8080/ui/js/controllers.js` at line 451:
```javascript
...
    $scope.add = function() {
        var thingUID = $scope.thingType.UID + ':' + $('paper-input#id').val();
        var thing = {
            UID : thingUID,
            configuration : {}
        };
        // It's here!
        $.each($scope.thingType.configParameters, function(index, parameter) {
            thing.configuration[parameter.name] = $('paper-input#' + parameter.name).val();
        });
        thingService.add({
            'thingUID' : thingUID
        }, thing, function(response) {
            $scope.navigateTo('things');
            $scope.showSuccessToast('Thing added.');
        });
    };     
...
```
```
TypeError: Cannot read property 'length' of undefined
    at Function.n.extend.each (jquery.min.js:2)
    at k.$scope.add (VM706 controllers.js:457)
    at angular.js:10795
    at angular.js:19036
    at k.$eval (angular.js:12632)
    at k.$apply (angular.js:12730)
    at paper-fab.<anonymous> (angular.js:19035)
    at paper-fab.n.event.dispatch (jquery.min.js:3)
    at paper-fab.r.handle (jquery.min.js:3)
```
For-each assumes that thing has config parameters, but it may have no parameters like my simple thing. When I commented out for-each, thing has been created.

I can send patch for controllers.js, but where is a Paper UI repository?

**Comment by maggu2810** [comment]
IMHO: https://github.com/dnobel/openhab2/tree/paper-ui/

**Comment by kaikreuzer** [comment]
@dnobel, can you help? Note that I did not yet include the latest version of the Paper UI in the openHAB 2 distribution - I will do so in the next days, maybe this already fixes the problem...

**Comment by dnobel** [comment]
I can confirm that this is still a problem. At the moment the Paper UI assumes, that each thing has at least one config property. I think I can easily fix this. Will try it later.

**Comment by dnobel** [comment]
@dsalychev If you want to create PR against my fork of openHAB, please feel free to do so. The plan is to contribute the Paper UI soon to the openHAB2 repo.

**Comment by sja** [comment]
There seemed also be a problem on creating things without any group. Should be fixed with PR 7.

**Comment by dsalychev** [comment]
Did you fix it? I'd like to close the issue.

**Comment by kaikreuzer** [comment]
FTR: From today on, the PaperUI lives here: https://github.com/openhab/smarthome/tree/master/addons/ui/org.eclipse.smarthome.ui.paperui
We plan to move it over to the "official" Eclipse SmartHome git repo, but that might take a while.
And yes, this bug has already been fixed in the code, I will soon make a current version available in openHAB 2.
