### ISSUE TITLE
CometVisu backend

### ISSUE THREAD

**Issue by peuter** [openhab/openhab2#173]
I am currently developing an new version of the cometvisu backend, which will support everything the old version did, plus:
* PHP Support: CometVisu´s Config editor, config_check, ...)
* Sitemap support: generate a cometvisu config from a openHAB sitemap (as a starting point to customize the config for you own needs)
* GroupItems support: group-functions work like they do in other openHAB UI´s
* Persistence support: create charts from all persisted items (no more limit to RRD4J persistence)
* SSE support; no need to use atmosphere anymore

Developing versions of cometvisu binding:
https://github.com/peuter/openhab2/tree/cometvisu2

Developing version of cometvisu client:
https://github.com/peuter/CometVisu/tree/develop

Support for discovery of new things will not be possible, as the CometVisu would have completely reloaded after changes. But something like the "default" sitemap in the classcui should be possible, where discovered things are added to automatically.

**Comment by kaikreuzer** [comment]
Great to hear that you are working on porting the comet visu!

**Comment by teichsta** [comment]
out of curiosity, does list above also reflect the expected implementation order? From my point of view the SSE would be quite interesting in order to reactivate the status quo while the other issue seem to be an enhancement.

Best, Thomas E.-E.

**Comment by peuter** [comment]
No, the order is randomly. And its all implemented yet, I just need some time to test, cleanup everything.

**Comment by teichsta** [comment]
great, thanks for this update! Any idea when you will find the time?

**Comment by peuter** [comment]
I´m on it. I have just one main problem left.
I´m using a config file in conf/services/cometvisu.cfg, added the 
service.pid org.eclipse.smarthome.cometvisu and implemented the 
ManagedService.
I can read the config-file-settings from the ConfigurationAdmin-Service 
but the update()-method is never called after I change the cometvisu.cfg 
file. What am i missing?

Am 14.04.2015 um 13:11 schrieb Thomas Eichstädt-Engelen:

**Comment by kaikreuzer** [comment]
have a try with the service pid org.openhab.cometvisu instead.

**Comment by peuter** [comment]
doesn´t work either.

Am 14.04.2015 um 14:34 schrieb Kai Kreuzer:

**Comment by kaikreuzer** [comment]
Do you have a link to your branch to have a look?

**Comment by peuter** [comment]
Sure, here´s the File:
https://github.com/peuter/openhab2/blob/cometvisu2/bundles/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/servlet/CometVisuApp.java
And the corresponding osgi-xml:
https://github.com/peuter/openhab2/blob/cometvisu2/bundles/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-frontend-app.xml

Am 14.04.2015 um 14:34 schrieb Kai Kreuzer:

**Comment by kaikreuzer** [comment]
I cannot directly find the problem at a first glance at your code. But I have some comments anyway:
- Using ManagedService is a bit outdated and we have moved away from this in openHAB 1 as well. Instead, an OSGi service can directly receive its configuration through the activate() method. Please see https://github.com/openhab/openhab/wiki/How-To-Implement-A-Binding#global-binding-configuration for details.
- As the comet visu bundle will be an addon, it should be moved from bundles/ui to addons/ui (which needs to be created as we do not yet have any other UI addons)
- Related, we should not at all talk about a binding here - a binding is really for connecting to devices/services, but does not relate to a UI.

**Comment by peuter** [comment]
Ok I found the problem:

The components name has to be the same as the service.pid. I dont know 
if this is a bug or on purpose.
If the name is right, you don´t even need to add the service.pid 
property (accidently found out, because i had a typo in the property 
servide.pid instead of service.pid)
  So just to clarify:

<scr:component...name="org.openhab.ui.cometvisu.servlet.CometVisuApp">
<property name="service.pid" type="String" value="org.openhab.cometvisu"/>
not working

<scr:component...name="org.openhab.cometvisu">
working (event if you don´t use the service.pid property, or set it to a 
wrong value)

so it seems as if the service.pid property is ignored.


Am 15.04.2015 um 10:14 schrieb Kai Kreuzer:

**Comment by kaikreuzer** [comment]
> so it seems as if the service.pid property is ignored.

Yep, this seems to be the case.

**Comment by cloewen** [comment]
I’ve tried to get this version running. The addon seems to start and register. 
15:37:16.438 [DEBUG] [cometvisu.internal.CvActivator:45   ] - SSE API - SseFeature registered.
15:37:16.440 [DEBUG] [cometvisu.internal.CvActivator:54   ] - SSE API has been started.
I can connect to the configuration editor but when i try to preview the visu i get a reference error: Can't find variable: CometVisuOh. Also the path /rest/cv is missing. Do you think the current state of work is ready for 3rd party testing?

**Comment by peuter** [comment]
If the path /rest/cv is missing the CV backend has not been loaded. The debug messages you mentioned only show that the bundle is loaded, which does not mean that everything else is workign either. Do you see any exceptions in the log?
The CometVisuOh-error is a problem on the client side, which version are you using?
Have you read the new documentation regarding the binding: https://github.com/peuter/openhab2/tree/cometvisu2/addons/ui/org.openhab.ui.cometvisu
The CV binding is working quite well in my development envorinment, so I thought it would be ready to be reviewed and tested to show up the problems I did´t find yet. As this is a quite big update I´m sure that there are plenty of them.

**Comment by teichsta** [comment]
Hi @peuter,

i am facing some problems, too getting the CometVisu to work currently. I am trying to make the UI available while starting out of my IDE. What i've done so far is:

* imported org.openhab.ui.cometvisu in my workspace (version from https://github.com/peuter/openhab2/tree/cometvisu2)
* activate the bundle in LaunchConfiguration
* forked https://github.com/peuter/CometVisu/tree/openhab2 and copied the ```src``` folder into ```distribution/openhabhome/runtime/web/```
* added cometvisu.cfg to ```openhabhome/conf/services
* added ```webFolder=runtime/web/src/``` and ```webAlias=/cometvisu``` parameter

Configuration seems to be properly applied

```
15:57:55.946 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->webAlias:/cometvisu, Parts 1
15:57:55.947 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->objectClass:[org.openhab.ui.cometvisu.servlet.CometVisuApp], Parts 1
15:57:55.947 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->service.pid:org.openhab.cometvisu, Parts 1
15:57:55.947 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->component.name:org.openhab.cometvisu, Parts 1
15:57:55.948 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->component.id:124, Parts 1
15:57:55.948 [DEBUG] [cometvisu.servlet.CometVisuApp:164  ] - Property: ->webFolder:runtime/web/src/, Parts 1
```

When calling "http://localhost:8080/cometvisu" i get 

```
15:59:55.875 [WARN ] [e.jetty.servlet.ServletHandler:628  ] - /cometvisujava.lang.NullPointerException: null
	at java.net.URLDecoder.decode(URLDecoder.java:136)
	at org.openhab.ui.cometvisu.servlet.CometVisuServlet.getRequestedFile(CometVisuServlet.java:247)
	at org.openhab.ui.cometvisu.servlet.CometVisuServlet.doGet(CometVisuServlet.java:207)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
```

anything else missing?

**Comment by peuter** [comment]
Just checked it myself. It seems as if you have to add a slash to the 
URL, like:
http://localhost:8080/cometvisu/

or directly load the auto-generated demo config with:
http://localhost:8080/cometvisu/?config=demo

**Comment by teichsta** [comment]
*ähem* that was easy ;-)

However calling ```http://localhost:8080/cometvisu/?config=demo``` leads to an

```
Config-File Error!
Invalid config file!
Please check!
```

The log says 

```
16:58:52.661 [DEBUG] [u.c.internal.config.VisuConfig:179  ] - Item 'Outdoor' could not be found in the item registry
16:58:52.663 [WARN ] [s.u.i.items.ItemUIRegistryImpl:570  ] - Group 'null' could not be found.org.eclipse.smarthome.core.items.ItemNotFoundException: Item 'Outdoor' could not be found in the item registry
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.getItem(ItemRegistryImpl.java:127)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getItem(ItemUIRegistryImpl.java:623)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getDynamicGroupChildren(ItemUIRegistryImpl.java:556)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getChildren(ItemUIRegistryImpl.java:538)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.processWidget(VisuConfig.java:184)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.processWidget(VisuConfig.java:195)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.createPages(VisuConfig.java:145)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.getConfigXml(VisuConfig.java:109)
	at org.openhab.ui.cometvisu.servlet.CometVisuServlet.doGet(CometVisuServlet.java:219)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

and

```
17:07:28.482 [DEBUG] [o.u.c.servlet.CometVisuServlet:213  ] - reading sitemap 'org.eclipse.smarthome.model.sitemap.impl.SitemapImpl@4198becd (name: demo, label: Main Menu, icon: null)'
17:07:28.490 [DEBUG] [u.c.internal.config.VisuConfig:97   ] - requestPath '/config/visu_config_demo.xml' has '2' parts
17:07:28.493 [INFO ] [c.internal.config.ConfigHelper:77   ] - icon mapping enabled: null, 0 known mappings
17:07:28.515 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.517 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.518 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.521 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.523 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.525 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.527 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.529 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.536 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.537 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.537 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.538 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.538 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.538 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.539 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.539 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.539 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:07:28.984 [ERROR] [u.c.internal.config.VisuConfig:132  ] - nulljavax.xml.bind.MarshalException: null
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:116)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.marshal(VisuConfig.java:129)
	at org.openhab.ui.cometvisu.internal.config.VisuConfig.getConfigXml(VisuConfig.java:111)
	at org.openhab.ui.cometvisu.servlet.CometVisuServlet.doGet(CometVisuServlet.java:219)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'widgetinfo'. One of '{infowidget}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:458)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3237)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1796)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
```

First one seem to be due to an error in the ```demo.items``` (or ```demo.sitemap```) but second doesn't disappear …

**Comment by peuter** [comment]
Yes as far as I remember there is an error in the demo.sitemap. In the 
first frame there is a group item named Outdoor, which does not exist in 
the demo.items (IMHO should be renamed to Garden).

The second error is due to my outdated cometvisu branch. Meanwhile the 
OH2-parts (and more) have been merged in to the main development branch:
https://github.com/CometVisu/CometVisu/tree/develop

so you should use this one for testing.

**Comment by teichsta** [comment]
> so you should use this one for testing.

changing to "develop" and calling ```http://localhost:8080/cometvisu/?config=demo``` removed the error but leads to a "Loading…" page which loads forever.

(thanks for the quick replies)

```
17:29:30.466 [DEBUG] [.e.s.m.i.i.GenericItemProvider:121  ] - Read items from model 'demo.items'
17:29:50.650 [DEBUG] [o.u.c.servlet.CometVisuServlet:213  ] - reading sitemap 'org.eclipse.smarthome.model.sitemap.impl.SitemapImpl@4c47c5 (name: demo, label: Main Menu, icon: null)'
17:29:50.659 [DEBUG] [u.c.internal.config.VisuConfig:97   ] - requestPath '/config/visu_config_demo.xml' has '2' parts
17:29:50.663 [INFO ] [c.internal.config.ConfigHelper:77   ] - icon mapping enabled: null, 0 known mappings
17:29:50.688 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.691 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.691 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.694 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.697 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.698 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.700 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.702 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.704 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.711 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.712 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.712 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.712 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.713 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.713 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.713 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.714 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
17:29:50.714 [WARN ] [t.i.s.MapTransformationService:114  ] - Could not find a mapping for '-' in the file 'en.map'.
```

**Comment by peuter** [comment]
I guess that is the client problem I´m currently struggling with. A 
workaround should be to comment out lines 34 and 112 in 
src/lib/cometvisu-client-openhab.js

https://github.com/CometVisu/CometVisu/blob/develop/src/lib/cometvisu-client-openhab.js#L34
https://github.com/CometVisu/CometVisu/blob/develop/src/lib/cometvisu-client-openhab.js#L112

**Comment by teichsta** [comment]
some error in JS Console

```
[Error] ReferenceError: Can't find variable: CometVisuOh
	initBackendClient (templateengine.js, line 287)
	parseXML (templateengine.js, line 912)
	success (templateengine.js, line 162)
	fire (jquery.js, line 974)
	fireWith (jquery.js, line 1084)
	done (jquery.js, line 7803)
	callback (jquery.js, line 8518)
```

**Comment by peuter** [comment]
Yes thats exaclty the error I meant. Did you already apply the workaround? Sometimes you have to clear the browser cache or add &forceReload=true to the URL in order to get the changes JS file loaded.

**Comment by teichsta** [comment]
> &forceReload=true 

that did the trick :-) Now i see the demo sitemap … Thanks!

**Comment by teichsta** [comment]
wouldn't it be better have the workaround applied on "develop" automatically? Since the branch should contain a working Software (read that in the Wiki) :-) ?

**Comment by peuter** [comment]
Congrats, btw. you can´t use the editor with the autogenerated demo sitemap, as there is also a "real" demo sitemap, which confuses the editor. Another thing on my TODO-list on the client side.

**Comment by peuter** [comment]
Yes, but the workaround only works for openHAB2 (and not for openHAB1 and the default cometvisu-backend). So the branch contains code, which works for the more used backends.
I have to find a solution, which works in all environments.

**Comment by teichsta** [comment]
ftr

> Yes as far as I remember there is an error in the demo.sitemap. In the
first frame there is a group item named Outdoor, which does not exist in
the demo.items (IMHO should be renamed to Garden).

see https://github.com/openhab/openhab2/pull/196

**Comment by teichsta** [comment]
> I have to find a solution, which works in all environments.

ok, got you!

**Comment by peuter** [comment]
Fix for the workaround is found:
https://github.com/CometVisu/CometVisu/pull/167

**Comment by kaikreuzer** [comment]
This has been implemented with https://github.com/openhab/openhab2/pull/189
