### ISSUE TITLE
REST API: Cannot create Group with Tags

### ISSUE THREAD

**Issue by sja** [openhab/openhab2#175]
I saw, that I cannot add a group with tags. Swagger mentions, that I can do a POST to `/setup/groups` with the following:
```json
{
"label":"Kitchen",
"name":"home_group_123",
"tags":["MyTag"]
}
```
but that does not seem to work.

In ThingSetupManagerResource.java:195 I see `addHomeGroup()`. What is a Home Group? And why does ThingSetupManager always add a static Tag 'home_group'?

**Comment by kaikreuzer** [comment]
I'd suggest that you enter a bug at https://bugs.eclipse.org/bugs/buglist.cgi?product=SmartHome&component=Core&list_id=11409854 as this is code of ESH (and the /setup rest resource should not really be used in openHAB).

**Comment by sja** [comment]
I forgot, sorry.
