### ISSUE TITLE
Paper UI with drop menu

### ISSUE THREAD

**Issue by Shibonja** [openhab/openhab2#178]
I don't know is this is the right place for my question, but i place it here. Is it possible to make drop menu in Paper UI for parameters like there is one for group assignment?
I want to implement lirc binding, and because there are a lot of lirc remote configurations I hope to make a drop menu where the user first choose the manufacturer in a drop menu and as second parameter there will be a drop menu for remote models for specific manufacturer.

**Comment by kaikreuzer** [comment]
I don't think this is a question about the Paper UI - having a config parameter depending on the value of another parameter is currently not possible. I have already heard some discussions about dynamic selection lists, but I would suggest that we move such a core architectural discussion over to Eclipse SmartHome (https://www.eclipse.org/forums/index.php/f/271/).
