### ISSUE TITLE
Alpha Release or Snapshot Build?

### ISSUE THREAD

**Issue by bpair** [openhab/openhab2#181]
Hi. I downloaded openHAB a couple weeks ago. Since then I have read the plans for openHAB2 and it really seems to improve on openHAB. I would like to start building my sensor network with openHAB2.

The Alpha release was 4 months ago and I am wondering if you still suggest starting there or going with a snapshot? or maybe a beta release is planned very soon?

thanks for all your hard work openHAB2 looks awesome..

**Comment by kaikreuzer** [comment]
Most likely it is best to go for the snapshot build as it has evolved quite a bit already. Just be aware that what is shown in the screencasts might not apply anymore in very detail as they were done based on the alpha release.
I’m planning to do an alpha2 soon, before heading for a first beta release.

Best regards,
Kai
