### ISSUE TITLE
Managing items and sitemaps - API?

### ISSUE THREAD

**Issue by grzech1983** [openhab/openhab2#183]
Hello,

I'm looking from time to time on OH2 and hoping that sooner than later I will switch to it from OH1 to OH2. Actually a lot of things are working fine but one thing keeps me wondering and it is managing items and sitemaps using HABmin2. I've asked question about it to cdjackson and he responded to my question:

One more thing about habmin2: where I can find items and sitemaps (I know I can browse sitemap but where I can edit it?) configuration?

Not yet implemented. As yet there’s no interface in OH2 to do this - I could implement this in HABmin like I did in OH1, but I’d prefer to do it with the proper interface. Kai started a thread on this in the ESH forum a few weeks back which I replied to, but there’s been no further responses :(

So is there any chance for proper interface in OH2 for managing items and sitemaps?

Regards

**Comment by xsnrg** [comment]
The Eclipse Designer is working pretty well for configuration file management on OH2.

**Comment by grzech1983** [comment]
Hello,

Does Eclipse Designer allows to edit items and sitemaps when OH2 is running on remote machine without need to restart OH2? IMHO if it not allows that then we are talking about two different things here. Preparing whole environment can be done "offline" but when it is running and you want to add things (items, rules or edit them) from automation software is expected to make possible this kind of changes online (here with HABmin). 

Regards

**Comment by teichsta** [comment]
@grzech1983 since this seems to be general technical discussion please ask and discuss on the Google Group. Thanks, Thomas E.-E.

**Comment by grzech1983** [comment]
IMHO my first message was not a technical discussion. Developer of HABmin2 cdjackson (https://github.com/cdjackson/HABmin2/issues/25#issuecomment-90882462) wants to add sitemap and items edit possiblity but he can't because there are no interfaces for that in OH2 and I've decided to send this issue report.

**Comment by teichsta** [comment]
ok, but that would be an ESH core issue for which an issue has been created already, right?

**Comment by maggu2810** [comment]
@grzech1983 
If there has not been any fundamental changes, you are right. The designer is used to change files on the local filesytem.

I agree with @teichsta that this should be a feature request or a discussion that is related to ESH.
Perhaps you could start a topic on the Eclipse SmartHome forum or the bug tracker for ESH (there is no issue support on the github page).

**Comment by cdjackson** [comment]
For sitemaps, there is a thread here (https://www.eclipse.org/forums/index.php/t/1064113/ <https://www.eclipse.org/forums/index.php/t/1064113/>).

**Comment by kaikreuzer** [comment]
Items are already manageable through the REST API, for sitemaps see the link that @cdjackson just posted.

**Comment by grzech1983** [comment]
Ok. Thaks. Regarding eclipse smarthome and OH2 I was getting impression that they are build on the same foundation but somehow different and separately developer projects so thats why I've also post issue here.

**Comment by teichsta** [comment]
please have a look at http://kaikreuzer.blogspot.de/2014/11/openhab-16-and-20-alpha-release.html which might clarify things …
