### ISSUE TITLE
Copyright statement need update(s)

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#200]
Fix year number to 2015 (instead of 2014), and maybe bring in line with, if any, changes made in the ESH statements
Adjust also in skeleton generators?

**Comment by kgoderis** [comment]
Partly done in https://github.com/openhab/openhab2/commit/0e5fc4b8e7256853519f5fba4a84e62da691b6ed

**Comment by kaikreuzer** [comment]
I do this once in a while, no need to add an issue for it. Some PRs still have old headers and get merged like that.
I will soon provide a new IDE setup mechanism and I will incorporate the ESH code formatter in it - with this in place, I will do a complete code clean up together with the headers.
