### ISSUE TITLE
MAP unavailable?

### ISSUE THREAD

**Issue by theArch2** [openhab/openhab2#205]
Hi,

i'm creating some sitemap and have problems with mappings:
```
19:45:53.973 WARN  o.e.s.c.transform.TransformationHelper[:37] - Cannot get service reference for transformation service of type MAP
19:45:53.973 WARN  o.e.s.u.i.items.ItemUIRegistryImpl[:345] - couldn't transform value in label because transformationService of type 'MAP' is unavailable
```

This is my item-config:
```
Contact someroom_window1 "Fenster Serverraum [MAP(de.map):%s]" (some_group)
```

This is my de.map:
```
CLOSED=Zu
OPEN=Offen
TILTED=Kipp
undefined=unknown
```

Is this a bug or a fail in my configuration?

Thanks

**Comment by kaikreuzer** [comment]
I just tested it on the current code of openHAB 2 and all works as expected.
If the problem still remains for you, please provide details on what version you exactly use and whether you run it from the IDE or from the distribution.

**Comment by theArch2** [comment]
I'm running the 2.0.0-alpha1 release at CentOS 7.0

**Comment by kaikreuzer** [comment]
Ok, better try with a recent snapshot from https://openhab.ci.cloudbees.com/job/openHAB2/

**Comment by theArch2** [comment]
Nice, with this snapshot it's running fine, thanks :)
