### ISSUE TITLE
Windows build does not start with included batch files

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2#215]
Using the snapshots from cloudbees, the windows builds don't start when clicking the 2 .bat files.
Issue most likely is due to wrong reference to the directories.

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/openhab/openhab2/pull/216

**Comment by marcelrv** [comment]
@kaikreuzer,

Actually, I found some more issues with the bat windows file having the wrong path.
like wrong path for:
-Dorg.quartz.properties=./runtime/etc/quartz.properties ^
-Djava.security.auth.login.config=./runtime/etc/login.conf ^

Also something is wrong with the jetty config. for that one I have not found out exactly what it is.
e.g. with the current file the jetty server does not start it seems

**Comment by kaikreuzer** [comment]
ok, the bat files probably need to be synced with the sh files. But probably not worth to spend to much effort as they will anyhow completely change if we do https://github.com/openhab/openhab2/issues/194.
