### ISSUE TITLE
Use curl redirection for commit hook script

### ISSUE THREAD

**Issue by hoegertn** [openhab/openhab2#219]
To download the git hook use -L as curl option to follow the redirect github is sending

**Comment by kaikreuzer** [comment]
Not sure what this is about. Is this a suggestion to change something? Is it a documentation hint? Is it possible to create a PR instead?

**Comment by hoegertn** [comment]
Hi, sorry I did not have the time to fix it by myself. I will create a Pull Request today. I just came across this issue when setting up my local dev environment.

**Comment by kaikreuzer** [comment]
Added by https://github.com/openhab/openhab2/pull/221
