### ISSUE TITLE
Error after setting up ide

### ISSUE THREAD

**Issue by Shibonja** [openhab/openhab2#222]
Hi, guy's., first I must say great work with OH2. 
So now my problem, I hope you can help me to solve it. Eclipse is getting errors when the method setStatus is used ("The method setStatus(ThingStatus) is undefined for the type Thing"). The problem came up after i was setting up eclipse ide for OH2 development. I followed the instructions on youtube from Kai, and first it was fine, I was able to play with OH2 (made some simple bindings), but after setting up the ide for the second time i cant get rid of this error. I am using Yoxos Launcher 5.6 with eclipse Luna SR2 on ubuntu 14.04 with JavaSE-1.7 (java-7-openjdk-amd64).
Please help father's of OpenHab 2

**Comment by kaikreuzer** [comment]
You seem to have an outdated version of the openHAB 2 source code (the method setStatus has been recently removed in ESH and I have updated the OH2 source code accordingly. Could you try to pull in the latest changes from master?
