### ISSUE TITLE
Host bundle 'org.eclipse.smarthome.ui.paperui' cannot be resolved

### ISSUE THREAD

**Issue by mathiasimmer** [openhab/openhab2#225]
I have just pulled the latest commit into a fresh IDE but I get an error in the newly added PaperUI bundle in the manifest file at line 7:
Host bundle 'org.eclipse.smarthome.ui.paperui' cannot be resolved

**Comment by kaikreuzer** [comment]
You can either:
- ignore this
- install the Paper UI in your workspace (see https://github.com/openhab/openhab2/blob/master/docs/sources/development/ide.md#paper-ui)

I'll try to add the Paper UI to the target platform soon, so that this is not necessary anymore.

**Comment by bjhiltbrand** [comment]
I just copied the master branch using git, and it had this problem. I don't know if the paper ui should have been officially added, but it wasn't on my copy. Just thought I would let you know.

**Comment by kaikreuzer** [comment]
It is now part of the target platform: https://github.com/openhab/openhab2/blob/master/targetplatform/openhab.target#L132
So you should reload this as well.
