### ISSUE TITLE
How to build and deploy?

### ISSUE THREAD

**Issue by mathiasimmer** [openhab/openhab2#226]
I have tried to fiddle with a new binding and a few other things and it works fine when running from Eclipse, but how can I build the system and actually try to deploy it on my Raspberry Pi?
I have tried running "mvn install" in the root directory and it generates a somewhat familiar looking zip-file but whenever I run the start.bat file, I get an error: No equinox launcher in path "runtime/server" found! - So I suppose something went missing in the build process?

**Comment by kaikreuzer** [comment]
For running it on your RaspPi, you should not use start.bat, but rather start.sh :-)
start.sh should work fine - with the bat scripts for Windows there currently seem to be some problems, see https://github.com/openhab/openhab2/issues/215

**Comment by mathiasimmer** [comment]
Yea I forgot to clarify that I tried to run on my Windows machine before running on the Raspberry Pi. I presumed that it wouldn't work on the Raspberry if it did not on my local machine :)
But I found out that I had to run "mvn clean package" (as specified in the documents! Doh!) instead of "mvn install"

**Comment by kaikreuzer** [comment]
```mvn install``` should be just as fine.
