### ISSUE TITLE
Problem getting state text

### ISSUE THREAD

**Issue by mathiasimmer** [openhab/openhab2#229]
I think something has changed in a recent update of the Paper UI, because I am no longer to read the state value of a specific field (others works fine), that used to work just fine.
Here is how it is being displayed:
![image](https://cloud.githubusercontent.com/assets/8802601/7491110/7d2ae9bc-f3e6-11e4-855f-8770e97d461f.png)
I get the following error code in the browser console:
```
SyntaxError: [sprintf] unexpected placeholder
    at Function.b.parse (sprintf.js:151)
    at b (sprintf.js:17)
    at n.$scope.getStateText (controllers.control.js:77)
    at ib.functionCall (angular.min.js:199)
    at Object.<anonymous> (angular.min.js:107)
    at n.$get.n.$digest (angular.min.js:123)
    at n.$get.n.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at M (angular.min.js:85)
    at XMLHttpRequest.F.onload (angular.min.js:86)
```

The peculiar thing is that it still works if the field is not set to read-only (and the console contains no errors):
![image](https://cloud.githubusercontent.com/assets/8802601/7491142/c7893072-f3e6-11e4-8912-547901227359.png)

**Comment by kaikreuzer** [comment]
The fact that your screenshots have green and not orange buttons shows me that you do not seem to use the latest PaperUI, which is contained in the target platform of OH2. You should not have any org.eclipse.smarthome.ui.paperui project in your workspace.

**Comment by mathiasimmer** [comment]
I think I have the latest version now. At least the colors are different now, but the same problem still persists:
![image](https://cloud.githubusercontent.com/assets/8802601/7492100/a62f37b4-f3f0-11e4-8513-b7ac71eee222.png)

**Comment by kaikreuzer** [comment]
@dnobel any idea?

**Comment by xsnrg** [comment]
When extracting the latest SNAPSHOT, I have two jars for paperui:

-rw-rw-r--+ 1 root root 3279425 May  6 03:06 org.eclipse.smarthome.ui.paperui-0.8.0-SNAPSHOT.jar
-rw-rw-r--+ 1 root root   17496 May  6  2015 org.openhab.ui.paperui-2.0.0-SNAPSHOT.jar

source:  https://openhab.ci.cloudbees.com/job/openHAB2/lastSuccessfulBuild/artifact/distribution/target/distribution-2.0.0-SNAPSHOT-runtime.zip

**Comment by dnobel** [comment]
Can you please write the item configuration? Is it a DateItem? What is the label?

**Comment by dnobel** [comment]
> When extracting the latest SNAPSHOT, I have two jars for paperui:

This is correct. One is the original Paper UI coming from smart home, the other is an openhab2 specific fragment bundle, which brings the branding. If you only install the org.eclipse.smarthome.ui.paperui bundle, you will see the pure Paper UI with a blue color.

**Comment by mathiasimmer** [comment]
We are adding Things at runtime so we have no item configuration to share unfortunately. But yes the Item is of type "DateItem" and the label is simply "Date"

**Comment by mathiasimmer** [comment]
I had a look at the eventstream and can see that the correct value is definitely being transmitted, so I would say it is client-side related.
![image](https://cloud.githubusercontent.com/assets/8802601/7560539/7928e134-f7c4-11e4-9c88-798a835687d3.png)

**Comment by kaikreuzer** [comment]
The Paper UI is now maintained in the openHAB Eclipse SmartHome Fork, so I would like to close this issue and have opened this one instead: https://github.com/openhab/smarthome/issues/11

**Comment by marcelrv** [comment]
@kaikreuzer is this item still tracked somewhere, I can't seem to find it.
I think it is still an open valid issue, but don't know if  it is open anymore somewhere.

This is the same behavior I see in #374

**Comment by kaikreuzer** [comment]
Did you create the issues I asked for in https://github.com/openhab/openhab2/issues/374#issuecomment-140017886?

**Comment by marcelrv** [comment]
yup... was writing it as you wrote your message ;)

**Comment by kaikreuzer** [comment]
Then it is tracked (now) :-)
