### ISSUE TITLE
add thing via rest api

### ISSUE THREAD

**Issue by Shibonja** [openhab/openhab2#230]
Sorry, if my post is misplaced. 
I need some help with rest API. I made a simple LDR binding for RPi that uses simple shell script for reading data. So, I have only one (string) channel. I have no auto discovery service. My question is. "how can i add the item via rest API, and not using paper UI binding. In http://localhost:8080/restdocs/things i found that for adding new thing parameters: "paramType", "type" and "required" parameters are needed, but i don't know what to put in these fields"?.

Thanks a LOT.

**Comment by Shibonja** [comment]
I found the solution by my own. 
Send POST request to addres: http://localhost:8080/rest/setup/things
wit json: {"UID":"ldr:ldr:aa29f6c5","configuration":{},"item":{"label":"ble Binding Thing","groupNames":["gFF","gGF"]}}

but thanks.

**Comment by kaikreuzer** [comment]
The "normal" way to create a thing is through the things endpoint, see https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/thing/ThingResource.java#L176

The setup endpoint is a convenience service that can also take care of creating items and links at the same time - if this is what you want, then all is fine.
We will work on a documentation for the REST API soon, sorry that this is still missing...
