### ISSUE TITLE
openHAB 2 needs OSGi™ Core Release 6

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#248]
The "Dashboard UI" forces "OSGi™ Core Release 6".
Is this really necessary?

<pre>
Bundle-Name = openHAB Dashboard UI
Bundle-SymbolicName = org.openhab.ui.dashboard
Bundle-Vendor = openHAB.org
Bundle-Version = 2.0.0.201505230103

Export-Package = 
        org.openhab.ui.dashboard
Import-Package = 
        javax.servlet;version=3.1.0,
        javax.servlet.http,
        org.apache.commons.io;version=2.2.0,
        org.osgi.framework;version=1.8.0,
        org.osgi.service.component,
        org.osgi.service.http,
        org.slf4j
</pre>

* "OSGi™ Service Platform Release 4 Core Specification Version 4.3" org.osgi.framework version 1.6
* "OSGi™ Core Release 5": org.osgi.framework version 1.7
* "OSGi™ Core Release 6": org.osgi.framework version 1.8

Karaf 4.0.0.M2 supports (out of the box) Equinox 3.9.1.v20140110-1610 (belongs to #194).

<pre>
Bundle-Name = OSGi System Bundle
Bundle-RequiredExecutionEnvironment = J2SE-1.5
Bundle-SymbolicName = org.eclipse.osgi; singleton:=true
Bundle-Vendor = Eclipse.org - Equinox
Bundle-Version = 3.9.1.v20140110-1610
</pre>

That exports "org.osgi.framework" version=1.7.

**Comment by maggu2810** [comment]
Same for org.openhab.binding.freebox

**Comment by kaikreuzer** [comment]
Thanks for noticing!
