### ISSUE TITLE
Weather binding issues with OH2 build #186

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab2#252]
A few builds previous, the weather binding was modifed to work with OH2.  It worked for some days.  In the last couple of days, it stopped working, and this is the debug output:

userdata/logs/openhab.log:2015-05-25 23:34:56 [DEBUG] [o.o.b.w.i.bus.WeatherActivator:32   ] - Weather binding has been started.
userdata/logs/openhab.log:2015-05-25 23:34:57 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'weather.cfg'
userdata/logs/openhab.log:2015-05-25 23:34:59 [INFO ] [o.o.b.w.i.common.WeatherConfig:228  ] - ProviderConfig[providerName=WUNDERGROUND,apiKey=<redacted key>]
userdata/logs/openhab.log:2015-05-25 23:34:59 [INFO ] [o.o.b.w.i.common.WeatherConfig:232  ] - LocationConfig[providerName=WUNDERGROUND,language=en,updateInterval=5,latitude=41.731,longitude=-93.662,locationId=home,name=Saylorville Lake]
userdata/logs/openhab.log:2015-05-25 23:34:59 [DEBUG] [.w.internal.gfx.WeatherServlet:72   ] - Starting up weather servlet at /weather
userdata/logs/openhab.log:2015-05-25 23:35:02 [INFO ] [.o.b.w.i.s.WeatherJobScheduler:85   ] - Disabling weather locationId 'home', no binding available

I have not modified my weather.cfg nor my weather.items files.

I tried to change my weather.items down to a single line, but it does not make any difference.  I consistently receive the message "Disabling weather locationId 'home', no binding available even though it says the binding has been loaded.

The syntax for the .items and .cfg files checks out fine in the latest build of Smarthome Designer as well.

Thanks
Jim

PS.  I am going to move reporting for those bindings included with Alpha2 over to the OpenHAB2 issue log.  Please let me know if this is the right idea.

**Comment by kaikreuzer** [comment]
> PS. I am going to move reporting for those bindings included with Alpha2 over to the OpenHAB2 issue log. Please let me know if this is the right idea.

I think it is best to report the problems in the repository where the sources are located as well - and in the case of the weather binding, this is openHAB 1. Only if it turns out that something on openHAB 2 side needs to be adapted to make it work, we should track the issue here. Agreed?

**Comment by xsnrg** [comment]
Kai,

Leaving the issue with the source code makes sense.  The only reason I thought to move them here was running 1.x bindings with 2.0 OpenHAB is somewhat of a special case.  They should work in both places though, so this can be moved or just closed, see below.

Your suggestion of squashing the .items files together into a single also made this issue go away.  As simple as cat *.items >> master.items and a restart, and the weather binding is working again.  Is this still a bug, or is that just how it works?

Thanks,
Jim

**Comment by kaikreuzer** [comment]
> running 1.x bindings with 2.0 OpenHAB is somewhat of a special case.

I will soon ask people to make sure that their bindings are 2.0 compatible, so there should be rising awareness on openHAB 1 side.

Concatenating item files should not be necessary. If you can describe a simple reproducible problem, please file a bug report for it here.
