### ISSUE TITLE
Split org.openhab.core.init

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#253]
The org.openhab.core.init does e.g. create the UUID file and create the version file.
Additionally it sets up slf4j with all bridges for the different logging frameworks.

What to you think about split this into two separate bundles?

org.openhab.core.init import the package "org.slf4j.bridge", so we need to install e.g. org.slf4.jul, to get the bundle resolved at all.
If we want not to change the logging framework of e.g. Karaf, we should be able to left this OH2 feature, but get the version and UUID file created.

**Comment by kaikreuzer** [comment]
Wouldn't we simply have to remove the slf4j logging bridge code completely as Karaf takes care of setting up all logging infrastructure?

**Comment by maggu2810** [comment]
I believe we could do this, let's drop them if we switch to Karaf.
So, you prefer to use a local modified version till then?

**Comment by kaikreuzer** [comment]
> So, you prefer to use a local modified version till then?

Well, I would suggest to make all necessary changes on a branch, like I have started at https://github.com/kaikreuzer/openhab2/tree/karaf

**Comment by maggu2810** [comment]
Didn't we need to keep the bridge for running openHAB 2 in the Eclipse IDE?

**Comment by kaikreuzer** [comment]
Not sure, you can try it out. I think it might only mean losing logging messages from some libs (that e.g. use jul). The "normal" slf4j logging statements should still work, right?

**Comment by maggu2810** [comment]
> Wouldn't we simply have to remove the slf4j logging bridge code completely

I thought, we would perhaps keep the written code in a separate bundle and just deselect it. But if you feel good, get this code lost (let's say unavailable as bundle, git history keeps it), it is fine for me, too.

> I would suggest to make all necessary changes on a branch

Done for myself.

> Not sure, you can try it out. I think it might only mean losing logging messages from some libs (that e.g. use jul). The "normal" slf4j logging statements should still work, right?

Seems to be correct.

**Comment by kaikreuzer** [comment]
ok, so I think we can close this issue then, thanks.
