### ISSUE TITLE
JDWP-Handshake

### ISSUE THREAD

**Issue by Suplanus** [openhab/openhab2#256]
I have a problem running the demo of V2. Is running on MacOS X Yosemite with updated Java.
When i go to http://localhost:8001/ this is the debug output (handshake failed comes when url is entered):

```
rainbow:downloads moz$ cd openhab-2.0.0.alpha2-demo.zip\ Ordner/
rainbow:openhab-2.0.0.alpha2-demo.zip Ordner moz$ sudo ./start_debug.sh
Launching the openHAB runtime in debug mode...
Listening for transport dt_socket at address: 8001
osgi> Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - excepted >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - excepted >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - excepted >JDWP-Handshake<
```

The Browser shows this error (safari/chrome):
>ERR_EMPTY_RESPONSE

The problem was already there: https://groups.google.com/forum/#!topic/openhab/ymz_stwWbpg

**Comment by kaikreuzer** [comment]
> The problem was already there: https://groups.google.com/forum/#!topic/openhab/ymz_stwWbpg

Well, it was already answered there. 8001 is the JVM debug port and not a webserver. You still have to use port 8080 for your webbrowser.
