### ISSUE TITLE
Sonos Play mp3 from URL/Path

### ISSUE THREAD

**Issue by ArjunaWolfsteller** [openhab/openhab2#275]
Hey Guys,
I have added my SONOS system to Eclipse SmartHome /Openhab 2 with the PaperUI. I am able to start it via the rule:

------
    rule "say"
    when
        Item googletexttospeech_gTTS_GoogleTextToSpeech_StatusText changed
    then
        Thread::sleep(1000)    
        sendCommand(sonos_zoneplayer_RINCON_B8E93781285601400_control, PLAY)
    end
-------

But actually I don't want the SONOS just to start... I also want to commit the path (or URL) of the File?! Is this possible with PLAYURI? How does it work?

Thanks for help!!!
Arjuna﻿

Ps: Like I used to ask here:
https://groups.google.com/forum/#!topic/openhab2/0l67X0-LpOM

**Comment by kaikreuzer** [comment]
I have answered on https://groups.google.com/d/msg/openhab2/0l67X0-LpOM/0IijNiHHzx4J
