### ISSUE TITLE
persistence restoreOnStartup not working.

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab2#279]
Persistence is configured correct. When i use mysql data writes to mysql fine but not restored after openhab2 restarts. i tried to use rrd4j - same thing, date creates in userdata  but after restart not restored. Item is Switch. may be restoreOnStartup not working in openhab core?

**Comment by kgoderis** [comment]
See https://github.com/openhab/openhab2/issues/270

K

**Comment by brutevinch** [comment]
@kgoderis AHhah. I do not understand anything there) i'm not programmer. is it bug or my mistake?

**Comment by kgoderis** [comment]
A bug

**Comment by kaikreuzer** [comment]
duplicate of #270
