### ISSUE TITLE
LIFX White tone

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab2#284]
In iOS app LIFX i can choose whites from warm to cold, but in colorpicker trying choose white is useless.
How can i choose white tone from OH2? Please add support for whites.

**Comment by kaikreuzer** [comment]
As the LIFX binding comes from Eclipse SmartHome, might I ask you to add this feature request there (https://bugs.eclipse.org/bugs/buglist.cgi?list_id=12080989&product=SmartHome)?
