### ISSUE TITLE
LIFX connection error but LIFX app works fine!

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab2#286]
2015-06-21 15:07:32.847 [WARN ] [lifx.java.android.util.LFXLog ] - Idle timeout occured on UDP Connection lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection@cf4856, disconnecting

Thing lifx:light:light1 [ deviceId="D073DXXXXXXX" ]

Color ITM_LIGHT_BEDROOM_NIGHTLIGHT "Ночник" <light> (GR_ALL, GR_LIGHT_BEDROOM, GR_LIGHT, GR_BEDROOM) { channel="lifx:light:light1:color" }

Sometimes it works, sometime doesn't. Very unstable. 
Bulb has last firmware.
iOS APP LIFX works stable fine and HTTP API LIFX works too - network is ok.

**Comment by kaikreuzer** [comment]
@dnobel Do you know if this is a warning that is "normal" and thus should be ignored? If this is the case, we might want to adapt the logging level here.

**Comment by dnobel** [comment]
I have no idea. But even if we want to change it, it is logged inside the lifx-java-sdk lib. So we need to modfiy the library code.

**Comment by kaikreuzer** [comment]
Or change the logging for this class in the global logback.xml...
But as @brutevinch says it is also unstable, it probably should not be ignored.
@brutevinch, I'll close this issue as there is nothing that can be done on openHAB side (as the binding is from Eclipse SmartHome and the used library is a 3rd party one).
My hope is that we one day could switch LIFX support to AllJoyn, which might work more reliably.
