### ISSUE TITLE
Updating the Thing Structure

### ISSUE THREAD

**Issue by Shibonja** [openhab/openhab2#289]
Hi, guys.

I want to implement binding of a thing that has different numbers of channels, all channels are Switch type, but the number of switches are different from one thing to another, so I need a way to construct thing with channels dynamically. 

I found that ThingBuilder is used for updating the structure of a thing  from this link:
https://github.com/eclipse/smarthome/blob/master/docs/sources/architecture/thing-handler.md

protected void thingStructureChanged() {
    ThingBuilder thingBuilder = editThing();
    Channel channel = ChannelBuilder.create(new ChannelUID("bindingId:type:thingId:1"), "String").build();
    thingBuilder.withChannel(channel);
    updateThing(thingBuilder.build());
}

but i cant find the methods used in the example above.
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingBuilder.java
 
So, what is the best was to add manually channels. 
Thanks in advance, Haris.

**Comment by kaikreuzer** [comment]
Hi Haris,

Might I redirect you to the Eclipse forum (https://www.eclipse.org/forums/index.php/f/271/) with your question as it is fully related to Eclipse SmartHome APIs and docs?
