### ISSUE TITLE
my openhab companion cloud service for openhab 2

### ISSUE THREAD

**Issue by sidaga** [openhab/openhab2#294]
Hi,

is it possible to configure my openhab cloud companion service for openhab 2 ? I tried this service with openhab 1 it worked fine but its not working for openhab 2. Can anyone please guide me on how to proceed to on this issue ?

Thanks and regards
Siddhartha

**Comment by kaikreuzer** [comment]
Known limitation, see last point on https://github.com/openhab/openhab2/blob/master/docs/sources/intro.md.

Note that openHAB 2 is not meant for users, but only for developers at the moment - so my.openHAB support is not one of the highest prios for the moment.
