### ISSUE TITLE
EventPublisherDelegate should not depend on existence of item in ItemRegistry

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#296]
Under some circumstances, events are sent for items that are not yet available in the item registry. In such situations, the compatibility layer currently fails, see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab2/MT-kP1CV0x4/HdzArfHIUV8J for details.

**Comment by lolodomo** [comment]
Any update ?

**Comment by kaikreuzer** [comment]
Yes, absolutely! The dependency on the item registry has been removed with https://github.com/openhab/openhab2/commit/cf49c34c207edb270114451bf5bf259a092bfc3c.
