### ISSUE TITLE
Compile error in DefaultSitemapProvider with jdk 1.8

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2#298]
Code as of July 6th:

```
commit 1d4e9acaca0b7922e64d50148985cd28a4a8db6a
Author: Kai Kreuzer <kai@openhab.org>
Date:   Mon Jul 6 20:12:06 2015 +0200
```

Compiling with 1.8 gives

```
ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.openhab.core: Compilation failure: Compilation failure
ERROR] D:\work\openhab\openhab2\bundles\core\org.openhab.core\src\main\java\org\openhab\core\internal\item\DefaultSitemapProvider.java:[88]
ERROR] public Set<String> getSitemapNames() {
ERROR] ^^^^^^^^^^^^^^^^^
ERROR] The method getSitemapNames() of type DefaultSitemapProvider must override or implement a supertype method
ERROR] 1 problem (1 error)
ERROR] -> [Help 1]
```

Compiling the same source with 1.7 works perfectly.

**Comment by kaikreuzer** [comment]
I cannot confirm this - it works perfectly with Java 1.8 for me.
I rather assume that your build was executed against an older version of ESH bundles (which I also updated on the evening of July 6 on the p2 repo).
Could you try again today with the very latest openHAB 2 sources?

**Comment by hakan42** [comment]
I retried with the very latest sources and an empty maven repository (thus re-downloading the bundles). The compile works o.k. now with JDK 1.8. Thanks for looking into this :smile:
