### ISSUE TITLE
Astro binding causing NPE

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab2#299]
I have a custom config description provider for the zwave binding, and it's getting called with a null URI. Tracing this through, it's coming from the following code in ThingFactory -:

```java
        // initializing channels with default-values
        if (configDescriptionRegistry != null) {
            ConfigDescription cd = configDescriptionRegistry.getConfigDescription(type.getConfigDescriptionURI());
            if (cd != null) {
```

```type.getConfigDescriptionURI()``` seems to be returning null...

the parameters are -:
```ChannelDefinition [id=start, type=astro:start, properties={}]```
```ThingUID astro:sun:home```
```groupId rise```

If I disable astro in the debug config, then the system works... Given that it's illegal for getConfigurationDescription to be called with ```null``` this might also be considered a bug in *ESH*, but I'm guessing that there's probably also something wrong with the Astro binding as other bindings don't seem to do this.

I note that the astro binding defines the config description url ```thing-type:astro:config```, but I'm not sure if this is defined anywhere (it certainly doesn't appear to be in the XML - maybe there's a handler in the code).

**Comment by kaikreuzer** [comment]
This is all fine. The line that you mention actually requests config descriptions for a channel type, not a thing type. And so far we have no channels, which have any configuration - and thus also no configuration description.
But I agree that it is not nice to do the call with a null parameter. I have created a PR for ESH to avoid this.
