### ISSUE TITLE
[Reopen] Network Binding : "System Ping" always return true on Mac OS X server

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#300]
[Since I do not have the privilege to re-open an issue]

Following up on https://github.com/openhab/openhab2/issues/269

The problem persists. I do indeed get things like
  Created Network handler: 192.168.0.51;0;1;10000;5000;true
in the logs, but nothings else changes. The device is reported as being alive, whereas it is not in Mac OS X

**Comment by kgoderis** [comment]
With 
 - the jar you provided
 - , use_system_ping=false, refresh_interval=10000]

I get the correct results now. Should that be the case?

**Comment by TecSet** [comment]
> Created Network handler: 192.168.0.51;0;1;10000;5000;true
in the logs, but nothings else changes.

Okay, so the configuration is right. It sounds like a problem with Mac OS X Server Ping. I created a new jar which logs the output of Ping. Hopefully that clears things up: 
https://github.com/TecSet/openhab2/blob/network-test/addons/binding/org.openhab.binding.network/org.openhab.binding.network-2.0.0-SNAPSHOT.jar

> With
the jar you provided
, use_system_ping=false, refresh_interval=10000]
I get the correct results now. Should that be the case?

As far as I understand, use_system_ping=false has never been a problem. So yes there should be correct results.

**Comment by kaikreuzer** [comment]
@kgoderis Anything to do here?

**Comment by kgoderis** [comment]
No, not for the time being. I reverted back to the “internal” ping for now, and it seems to work. But I will retest in the future

**Comment by kaikreuzer** [comment]
Shall we close it for the moment or do you want to leave it open and "park" it?
