### ISSUE TITLE
Eclipse Installer: Add Plugin Development Environment

### ISSUE THREAD

**Issue by sfeilmeier** [openhab/openhab2#301]
With the new [Eclipse Installer](https://github.com/openhab/openhab2/blob/master/docs/sources/development/ide.md) building a package directly from Eclipse via "Export... | Plug-in Development | Deployable plug-ins and fragments" fails with this error:
> Problem: failed to create task or type apitooling.apigeneration
> Cause: The name is undefined.

This happens, because the "Plugin Development Environment" (PDE) is not installed by default. Installing it via "Help | Install New Software..." fixes the problem.

In my opinion the PDE should be installed with the Eclipse Installer, to enable building of single packages from Eclipse. What do you think?

**Comment by kaikreuzer** [comment]
Hi Stefan,

I very much agree, PDE must be part of the IDE! I will add it soon...

Thanks for pointing it out!
Kai

**Comment by kaikreuzer** [comment]
Added PDE - this should be automatically installed the next time you launch the IDE.
