### ISSUE TITLE
Provide icon for humidity

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2#303]
With PR #291 , @reitermarkus created a beautiful new icon set. What is still missing though is an icon for humiditiy, This is one of the values that is easily obtained from sensors like the DHT22 and very nice to show off openhab :smile:

**Comment by kaikreuzer** [comment]
@reitermarkus, want to have a try?

**Comment by reitermarkus** [comment]
Of course, I'll have a try. I'll also add a few icons which I recently created for my own use: Plex, Xbox One and Playstation.
