### ISSUE TITLE
Philips Hue Binding:  unsupported light 

### ISSUE THREAD

**Issue by funkstille** [openhab/openhab2#306]
While testing Philips Hue Binding I got the following error message:

2015-07-17 16:49:27 [DEBUG] [h.i.d.HueLightDiscoveryService:109  ] - discovered unsupported light of type 'LWB001' with id 3

Since the Living White Bulbs work perfectly with Philips Hue (http://www.everyhue.com/vanilla/discussion/229/10-adding-a-philips-living-whites-bulb-to-hue-network), they should be added as well.

THX

**Comment by kaikreuzer** [comment]
Since the Philips Hue binding is maintained at Eclipse SmartHome, may I ask you to enter this issue there? https://bugs.eclipse.org/bugs/buglist.cgi?list_id=12238885&product=SmartHome Thanks!
