### ISSUE TITLE
Startup failure - Could not find bundle: org.eclipse.equinox.console

### ISSUE THREAD

**Issue by sprotty** [openhab/openhab2#307]
Hi 

I'm new to openHab, and have been looking at trying to get the Alpha or trunk source to build and run. But I keep hitting against the same issue, when I run the start.bat/start.sh it appears to hang but in the equinox-SDK-Mars\configuration folder I get log file with the error below. I'm running the latest Java vm 1.8r51 and the latest equinox Mars sdk on a 64bit windows machine. I've done plenty of messing around with osgi.bundles commands, and the missing bundles (org.apache.felix.gogo.command, org.apache.felix.gogo.runtime, org.apache.felix.gogo.shell, org.eclipse.equinox.console), but the closest I got was no errors and it dropping into the osgi console...

I get the impression some of the dependencies of openhab have been re-structured and this may be the cause, but this is not my area, so a bit of help would be appreciated, if I could get started with this then there are quite a few areas I could test or contribute to. 

Simon

!SESSION 2015-07-21 13:01:13.561 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -console

!ENTRY org.eclipse.osgi 4 0 2015-07-21 13:01:14.069
!MESSAGE Could not find bundle: org.eclipse.equinox.console
!STACK 0
org.osgi.framework.BundleException: Could not find bundle: org.eclipse.equinox.console
	at org.eclipse.core.runtime.internal.adaptor.ConsoleManager.checkForConsoleBundle(ConsoleManager.java:58)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:331)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by kaikreuzer** [comment]
It is absolutely not clear to me what you are trying to do.
Do you
- try to run the maven build?
- install the IDE?
- launch the binary of the designer?

**Comment by sprotty** [comment]
Initially I'm just want to run the alpha runtime with the demo package.

I tried this on my windows box initially, and ran into the problem with 
missing bundles, I figured that maybe this was a windows quirk and put 
it on an Ubuntu 14 VM, which gave me the same error.

Are there specific versions of linux/java/eqinox that are known to work.

Thanks
     Simon

**Comment by kaikreuzer** [comment]
Have a try with the latest build from https://openhab.ci.cloudbees.com/job/openHAB2/lastSuccessfulBuild/artifact/distribution/target/distribution-2.0.0-SNAPSHOT-demo.zip
I just tested it successfully on Windows 8.1:
<img width="1215" alt="bildschirmfoto 2015-07-22 um 14 46 15" src="https://cloud.githubusercontent.com/assets/3244965/8825580/857138de-3080-11e5-987b-887342af2c98.png">

**Comment by steand** [comment]
To day I installed Build No. 284 from cloudebees:
The demo run's allready in a oracle VirtualBox :
```Linux vrpi2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux```  
the runtime on a Raspberry Pi 2 with:
``` Linux rpi2 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux```
both with:
```Oracle Java 1.8.```
I think somthing on your environment is wrong.
