### ISSUE TITLE
Redirect to dashboard does not respect X-Forwarded-Scheme

### ISSUE THREAD

**Issue by beowulfe** [openhab/openhab2#317]
The use of X-Forwarded-Scheme for running openhab behind a reverse proxy is documented here: 
https://github.com/openhab/openhab2/blob/master/docs/sources/configuration/jetty.md

However, the redirect that occurs from / to /start/index ignores the X-Forwarded-Scheme header and uses the request's scheme instead.

Related, the nginx example in the documentation can use $http_host instead of $host to work for non-standard ports as well.

**Comment by kaikreuzer** [comment]
Fixed through #318.
