### ISSUE TITLE
Access rest-api from php website (CORS) failure

### ISSUE THREAD

**Issue by boostchen** [openhab/openhab2#323]
When using openHAB 1.8, we can access rest-api from another php website by javascript. But in the new openHAB 2.0, access failure. Chrome browser console error information like these: XMLHttpRequest cannot load http://xxx. Origin http://localhost is not allowed by Access-Control-Allow-Origin.

**Comment by kaikreuzer** [comment]
See also https://github.com/openhab/openhab/pull/2672#issuecomment-109550476.

If there is anybody who knows how this can be changed, please provide a PR (I assume that this has to happen at Eclipse SmartHome anyhow?)

**Comment by Testato** [comment]
i confirm that the openhab/openhab#2672 (comment) is solved by OH 1.7.1
but appear a new problem, that i think it is very simple to solve: the PUT is blocked
https://github.com/openhab/openhab/issues/2999

**Comment by Stratehm** [comment]
I have opened the corresponding bug on Smarthome: https://bugs.eclipse.org/bugs/show_bug.cgi?id=478037

The PR is ongoing.

**Comment by kaikreuzer** [comment]
This has been implemented by now, see https://community.openhab.org/t/cors-problem-at-rest-api/3712/9?u=kai
