### ISSUE TITLE
additional icons

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab2#325]
@reitermarkus well done on the new icon sets!

I have some ideas for some others that would be quite handy if you have the time.

box fan
furnace fan
ceiling fan

the above 3 can be covered with a generic picture of a fan 

US/Japan outlet (110v, looks a bit different than across the pond)

battery - many devices report a battery status

Thanks for your consideration.
Jim

**Comment by reitermarkus** [comment]
I have added fan and battery icons. Will do the outlet icons when I have time again.
