### ISSUE TITLE
Introducing Notification popup or status bar on client  GUI

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#326]
Hi

I'm referring to both Android/IOS and Web client 

Is there a way to notify user that a request(e.g when user press on a switch button on or off )  is being processed?  I'm developing an add-on that requires the action to communicate with my own system gateway to turn on a light as an example but the turn around time could be a few seconds or more.  Hence,  I want to notify the user that the request is being processed and waiting for response either there is an error or request is successful.

**Comment by kaikreuzer** [comment]
No, the general concept is that of asynchronous communication; So a UI simply sends commands and the state of the item can change asynchronously any time later - which the UI can then react upon. As an alternative, you can also use a StringItem to report a system state or possible errors.
