### ISSUE TITLE
Unable to Display Text Item

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#329]
Hi
For some reasons, I can't get the the text to be displayed. What i get from the following is just [%s]. Is this a bug or configuration problem? Thanks

Thing Definition:

Bridge test:mainBridge:myHome [ urlAddress="https://192.168.253.112:7777", refreshInterval=15]
{ 
 .....
}

Item definition:
String MyMessage   "[%s]" {channel="test:mainBridge:myHome:message"}

Map definition:
Text item=MyMessage

Thing XML:
  <channel-type id="message">
        <item-type>String</item-type>
        <label>Display messages during runtime</label>
        <description>Show the messages </description>
    </channel-type>

Log from Eclipse:
2015-08-09 08:06:38 [INFO ] [smarthome.event.ItemStateEvent:43   ] - MyMessage updated to Hello
2015-08-09 08:07:02 [INFO ] [smarthome.event.ItemStateEvent:43   ] - MyMessage updated to Hello

**Comment by kaikreuzer** [comment]
Not sure about the exact problem, but as a workaround you might simply put a label to your sitemap:

Text item=MyMessage label="[%s]"
Regards,

Kai

**Comment by lsafelix75** [comment]
Not really solve the problem. I am still seeing %s to be displayed instead of Hello message
