### ISSUE TITLE
Allow HTTP(S) ports to be set without modifying startup scripts

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2#330]
I want to set up my OH2 installation with as pristine untouched files as possible. The hardcoded port numbers in the startup scripts make this hard (not impossible, just need a sed call per script, but still).

Injecting the HTTP and HTTPS ports to use from outside, via environment variables, makes it possible to create hands-off installations, and docker images, without needing to change the startup scripts.

**Comment by kaikreuzer** [comment]
Makes sense. Will you provide a PR?

**Comment by hakan42** [comment]
Here you go :smiling_imp:
