### ISSUE TITLE
Startup Time > 160sec on Raspberry Pi B+

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#341]
Hi

I downloaded the alpha2 distribution and attempted to run on my raspberry pi for testing. It tool 160sec to startup without addon, is this expected? Thanks

**Comment by xsnrg** [comment]
That sounds about right.  There is a fair bit of overhead, and the version 1 pi is not a speed demon.  Once loaded, it should be responsive enough though. That has been my experience anyway.

Jim
