### ISSUE TITLE
Automated documentation generation

### ISSUE THREAD

**Issue by kummerer94** [openhab/openhab2#348]
Hey there!

I had to help with the implementation of a binding recently and it really bothered me that I had to write the whole documentation by myself. (There were SO many channels...)

I saw some remarks in the Readme.md file in the maven-archetype that it is planned to generate some of the readme.

I want to help with that. Therefore, I created this simple Maven-plugin (https://github.com/kummerer94/binding-docu-generator). I headed out and created the necessary classes with XML annotations with JAXB and started coding.

You may want to take a look at the output: https://github.com/kummerer94/binding-docu-generator/blob/master/generated-docu.md

I looked through some of the existing documentation in the addons-directory of openhab2 and tried to make it look like the documentation there.

The plugin is able to:
* Parse the following XML types: thing-descriptions and config-descriptions.
* Based on the contents of the XML it will generate documentation for bridges, channels, channel-groups and types.
* It looks for available configuration (in the actual definition as well as in a config-description) and links it in the readme.

It is not fully functional currently for now. What needs to be done is the following:
* Look for the ESH-INF folder in the binding and find out which files need to be parsed.

The current implementation of the goal org.openhab:binding-docu-generator:generate-docu is hardcoded (so it will not dynamically look for existing XML-files but take the ones I told him to take):

```
parseThingDescripions(eshDir + "thing/channels.xml");
parseThingDescripions(eshDir + "thing/moon.xml");
parseThingDescripions(eshDir + "thing/sun.xml");
parseThingDescripions(eshDir + "thing/bridge.xml");
parseConfigDescriptions(eshDir + "config/config.xml");
```

The next steps would be to replace this and test the plugin with as many existing addons as possible and check the output of the plugin.

Cheers
Alex

**Comment by dnobel** [comment]
Hi,

just had a look into the Maven plugin: great work! It´s something we always had in mind, but we didn´t had the time to implement it.

I have a few comments:
* It would make sense to transfer this documentation generator to ESH, as the definition is part of the ESH core and could also be used for non-openhab-bindings
* Inside the Mojo you redefined all the already existing Java classes and you are parsing the XML files with JAXB. It would be better to use the Thing-Model from the ESH Core and also reuse the existing parser that is implemented with xstream. Otherwise we would have to maintain two Java models and two XML parsers. But I´m not sure how easy it is to include the according ESH OSGi bundles inside the Maven plugin
* You use a StringBuilder for generation the output. Did you think about using a simple template engine? I think it would be more flexible and easier to maintain

Regards

Dennis

**Comment by kummerer94** [comment]
Hey,

thanks for the comment, Dennis. The transformation would definitely make sense. I think I will continue to work on the plugin and open an issue at ESH for the first version.

For me, the plan was to parse the existing .xsd-files into Java code. I did not search in the ESH repository for the models. We do not really have to maintain two Java models as you can generate all the classes I have in my plugin with JAXB.

Although it would make sense to take the existing classes and use them to get the information. I will try to do that and we'll see how that works out.

About the StringBuilder: I was not really thinking long term when I wrote the plugin as I wanted to try how easy it is possible to code something like that. A template engine is a good idea. - Do you have any suggestion which template engine would be a good choice? I haven't worked with any in Java so far.

**Comment by dnobel** [comment]
Hi,

> For me, the plan was to parse the existing .xsd-files into Java code. I did not search in the ESH repository for the models. (Where are the models?)

There are here: https://github.com/eclipse/smarthome/tree/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type and https://github.com/eclipse/smarthome/tree/master/bundles/config/org.eclipse.smarthome.config.core/src/main/java/org/eclipse/smarthome/config/core

> We do not really have to maintain two Java models as you can generate all the classes I have in my plugin with JAXB. Although it would make sense to take the existing classes and use them to get the information. I will try to do that and we'll see how that works out.

we had different reasons why we didn´t used JAXB as parser: On the one hand you would have to add JAXB annotations to the core model (as you did) and on the other hand some Java embedded profiles do not support JAXB. That´s why the ESH parser is based on xstream. Unfortunately it seems not be ready to be used from outside. We would first need to refactor it, that´s a problem...

> A template engine is a good idea. - Do you have any suggestion which template engine would be a good choice? 

Mustache is a very lightweight but powerful engine: https://github.com/spullara/mustache.java Apache Velocity is even more powerful but might be to complex for simple markdown file generation. 

Regards

Dennis

**Comment by kummerer94** [comment]
Hey,

I tried using the existing models but this does not seem to work. I do not know enough about OSGi or how you implemented this to exactly tell why it is not working.

However, I will focus on the template engine as it is more important at the moment. I will think over the parsing thing.

After this is done I will move this issue to ESH. - Thank you so much for the help!

Regards

Alex
