### ISSUE TITLE
Persistence : RRD4j : lingering Timer Threads

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#358]
Just for the record, as per discussion on the ESH forum. 

rrd4j 1.8 in compat. mode instantiates a lot of Timer Threads, that linger around sporadically until the max. number of Threads of the JVM/OS is reached, which then cripples the OH2 runtime.

**Comment by kaikreuzer** [comment]
Is this ONLY when using it in OH2 or a general problem of the rrd4j addon? If the latter, please close this issue and only track it at openHAB 1.

**Comment by kgoderis** [comment]
As far as I can tell and see, this is a OH2 issue. I don't recall it being reported before by OH1 users, but on the other hand, I have no way to confirm it as I have no OH1 runtime/configuration set that I can verify against.

**Comment by kaikreuzer** [comment]
> this is a OH2 issue

An OH2 issue, but within the OH1 code (the rrd4j addon). So thanks for creating the PR there - let's see if this fixes the problem, I will close this issue, as we have https://github.com/openhab/openhab/pull/3131.
