### ISSUE TITLE
Error setting up openhab 2 IDE

### ISSUE THREAD

**Issue by sidaga** [openhab/openhab2#361]
https://dev.eclipse.org/recommenders/community/confess/#/incidents/5ecjWWrTHHSI3JwW2EXZyuRt1QqjSHGSkkHaR5qobCbCQKDBSS38mp8C6udQhhh0

**Comment by kaikreuzer** [comment]
Could you please provide some more info on how far you get, if it is reproducible, etc?

**Comment by sidaga** [comment]
I am using windows 7 32 bit,

I have:

Java 7 Update79
Java 8 Update 45
Java SE Development Kit 7 Update 79
Java SE Development Kit 7 Update 85

Installed.
Few days ago I tried IDE setup with yosox that time it worked fine and I tried myCoolStuff example binding it ran fine. 2 days ago tried it with the new eclipse installer and got around 4k errors I tried to reload the target platform then I believe that reload started downloading stuff from the internet but don't know if that process ended successfully or not I tried it 3-4 times, But still I am having no success in running openhab from eclipse.

**Comment by kaikreuzer** [comment]
Sorry, I cannot reproduce this. Just did a fresh install on Windows 8 for a test and all went smoothly.

So the IDE setup was successful and all that is missing is the resolved target platform?

**Comment by sidaga** [comment]
I tried again and ide setup working fine now.

Thanks and regards
siddhartha

**Comment by kaikreuzer** [comment]
Glad to hear that!
