### ISSUE TITLE
JSONPATH transformation

### ISSUE THREAD

**Issue by Tavalin** [openhab/openhab2#369]
Hi

I've downloaded a snapshot of openhab2 to test out.  I started by copying across my addons and config from my openhab set up and things seemed to run fine. However I noticed when using one of my more complex rules that there appears to be a feature missing.

My rule uses JSONPATH to transform a HTTP response into some data for my rule but I was presented with the following.

2015-09-10 17:48:52.280 [WARN ] [e.s.c.t.actions.Transformation] - No transformation service 'JSONPATH' could be found.

Is the JSONPATH transformation (or even transformations in general - I haven't tested others) something that hasn't found it's way into openhab2 yet? Or is there some other explanation?

Thanks

**Comment by teichsta** [comment]
Hi @Tavalin, the JsonPath Transformation is part of ESH since https://github.com/eclipse/smarthome/pull/350 so it will be available in OH2 after the next ESH release. Best, Thomas E.-E.

**Comment by kaikreuzer** [comment]
THanks @Tavalin for raising this issue. While it is already part of ESH (as @teichsta points out), I missed so far to add it to the openHAB 2 distribution, which I have now just done with https://github.com/openhab/openhab2/commit/711f0f0712546c9ada21f72669e1fc7e33213b3e.
The according snapshot build has just succeeded, so please test if it works and close the issue, if it does: https://openhab.ci.cloudbees.com/job/openHAB2/330/

**Comment by teichsta** [comment]
sorry, didn't know that …

**Comment by Tavalin** [comment]
@kaikreuzer I replaced the runtime folder and tried again but I still get the same issue.  I checked the runtime/plugins folder and can see org.eclipse.smarthome.transform.jsonpath_0.8.0.201509100907.jar.

Did I miss a step?

**Comment by kaikreuzer** [comment]
> Did I miss a step?

No you didn't. I'll try to debug myself tomorrow and see, why it still cannot be found :-|

**Comment by kaikreuzer** [comment]
I think I found the problem - the bundles are not automatically started. Fixed it with https://github.com/openhab/openhab2/commit/82c690418b21920414b89c0f0b047478d1c2ead0. Please try the next build https://openhab.ci.cloudbees.com/job/openHAB2/331/ when it is done.

**Comment by Tavalin** [comment]
It's working again - awesome!
