### ISSUE TITLE
FS20 (oh1): cul transport

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#372]
The FS20 bundle of the OH1 is compatible to OH2 (compatibility matrix).
The bundle imports "org.openhab.io.transport.cul".
* Is the transport bundle also compatible?
* Should we add this bundle to the compatibility matrix?
* Is the package provided by another bundle available in OH2?

**Comment by kaikreuzer** [comment]
> Is the transport bundle also compatible?

Afair: yes.

> Should we add this bundle to the compatibility matrix?

Not really, as it has no functionality of its own - we also do not list them as individual addons in the docu. For Karaf: Yes, this bundle should simply be part of the FS20 feature :-)

> Is the package provided by another bundle available in OH2?

No.

**Comment by maggu2810** [comment]
> For Karaf: Yes, this bundle should simply be part of the FS20 feature

I would prefer not closing this issue but assign a "Karaf" tag.

**Comment by maggu2810** [comment]
solved with 78fd371a0a99fb61f3ca14e71b3e8adacaa0ecc9
