### ISSUE TITLE
DateTime item-type not displaying consistently in classic UI / PaperUI

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab2#374]
I created a new binding for NTP in a OH2 way. However, having difficulties displaying the data.

When in the channel-type definition I define the channel with `<item-type>DateTime</item-type>`
and do the update `updateState(c.getUID(), new DateTimeType(calendar));`
It does not show consistently between the paper-UI and the classic UI.

If there is no `<state> `description, it displays fine in the paperUI, but it remains empty in the classic UI.
if I add `<state readOnly="true" pattern="%1$tA, %1$td.%1$tm.%1$tY %1$tT"></state> ` it displays fine in classic UI, but in paperUI it shows `{{getStateText(item)}}`

**Comment by kaikreuzer** [comment]
> If there is no <state>description, it displays fine in the paperUI, but it remains empty in the classic UI.

Could you please enter an issue for the Classic UI here: https://bugs.eclipse.org/bugs/buglist.cgi?product=SmartHome

> if I add <state readOnly="true" pattern="%1$tA, %1$td.%1$tm.%1$tY %1$tT"></state> it displays fine in classic UI, but in paperUI it shows {{getStateText(item)}}

And an issue for the Paper UI here: https://github.com/openhab/smarthome.paperui/issues

Thanks, and sorry for the re-directs :-)
