### ISSUE TITLE
Chart service attrib from sitemap not added to GET path for chart URL

### ISSUE THREAD

**Issue by grzech1983** [openhab/openhab2#378]
Hello,

I'm struggling to make operational charts for MySQL persistence. Since MySQL persistence started working correctly in OH2 now it is time for charts.

I've found out that even adding "service" attrib to Chart item in sitemap does not reflect chart image URL where is no service GET param. Example:

Sitemap:

Chart item=HEM_E label="Wykres zużycia prądu" icon="energy" period=D refresh=60 service=mysql

Generated URL:

/chart?items=HEM_E&period=D&random=1

This image does not generate any chart line (but chart x,y lines are being showed). When I manually add service=mysql GET param:

/chart?items=HEM_E&period=D&random=1&service=mysql

chart is being displayed correctly and I see in MySQL persistance log that SELECT query is being performed.

Does this is a bug or I didn't configured something somewhere?

Thanks

**Comment by kaikreuzer** [comment]
I cannot confirm this, in my tests it works perfectly.

Do you really have
```
Chart item=HEM_E label="Wykres zużycia prądu" icon="energy" period=D refresh=60 service=mysql
```
?
The Designer should actually mark this with a syntax error. Try
```
Chart item=HEM_E label="Wykres zużycia prądu" icon="energy" period=D refresh=60 service="mysql"
```
instead and it should work.
