### ISSUE TITLE
Structure distribution of Karaf based runtime

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#379]
This issue contains the TODOs of #370 for further tracking

* have the files in the root of the zip, i.e. not package them within a folder of the file name
* have Karaf within the runtime folder
* have start.sh/bat scripts that simply call runtime/bin/karaf
* configure KARAF_BASE to ${openhab.home}/runtime
* configure KARAF_DATA to use ${openhab.home}/userdata
* configure logging to log to /userdata/log/openhab.log
* Karaf deploy directory should be changed to '${openhab.home}/addons'
* don't break instances (move them to userdata)

Additional information:
* http://karaf.922171.n3.nabble.com/Karaf-installation-to-a-read-only-directory-td4040942.html
* Karaf bin/setenv[.bat]

**Comment by maggu2810** [comment]
@kaikreuzer could you tell me, how I can stop the eclipse bundle(s) to create a workspace directory?
After using the Karaf container a new directory was added

<pre>
workspace/
workspace/.metadata
workspace/.metadata/.log
workspace/.metadata/.plugins
workspace/.metadata/.plugins/org.eclipse.core.resources
workspace/.metadata/.plugins/org.eclipse.core.resources/.root
workspace/.metadata/.plugins/org.eclipse.core.resources/.root/.indexes
workspace/.metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
workspace/.metadata/.plugins/org.eclipse.core.resources/.safetable
workspace/.metadata/.plugins/org.eclipse.core.runtime
workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings
workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.core.resources.prefs
</pre>

**Comment by kaikreuzer** [comment]
I have no idea... As a workaround, try to make it at least create this directory within the userdata folder...

**Comment by maggu2810** [comment]
Already done. But there is still another problem... It is not so easy as it should be.

**Comment by maggu2810** [comment]
@kaikreuzer 
I checked in a working state.
Please test it and give me some feedback.

Check out my branch and build at least the whole distribution directory.
Then have a look at "openhab2-runtime/target/openhab2-runtime-2.0.0-SNAPSHOT.tar.gz"

>* have the files in the root of the zip, i.e. not package them within a folder of the file name

done

>* have Karaf within the runtime folder
>* configure KARAF_BASE to ${openhab.home}/runtime
>* configure KARAF_DATA to use ${openhab.home}/userdata

ATM (for testing) I used:
* karaf.base = ${openhab.home}/userdata/karaf-base
karaf.base seems to be the working directory and some stuff creates file at runtime...
* karaf.data = ${openhab.home}/userdata/karaf-data
Just to see what is created here...
* karaf.home = ${openhab.home}/runtime/karaf-home
Keep separate Karaf directory in runtime
* karaf.etc  = ${openhab.home}/runtime/karaf-etc
I think we should not mix plain OH2 etc and Karaf etc

>* configure logging to log to /userdata/log/openhab.log

The logging configuration file location will be set with: #384
I am correct?

>* have start.sh/bat scripts that simply call runtime/bin/karaf
ATM just created a start.sh, so you could have a look at it (and because I use it).

>* Karaf deploy directory should be changed to '${openhab.home}/addons'

This will be easy, just changing the fileinstall configuration.
Will do it later.

>* don't break instances (move them to userdata)

Haven't tested it.
ATM you will see a warning if you start and stop the Karaf container.
This is caused by a bug in Karaf (or a wrong assumption that karaf.home and karaf.base is the same location). JBO tries to fix that for Karaf 4.0.2
But it seems to working, ignoring the warning.

**Comment by kaikreuzer** [comment]
Wow, you again did a great job! It built and worked right away - I like it a lot :-)

Just a few small comments/suggestions:

> The logging configuration file location will be set with: #384
> I am correct?

Yes, sure, this can wait to be done in #384.

Regarding the folders, I would suggest to chose the directories like this:
```
export KARAF_HOME="${OPENHAB_HOME}/runtime/karaf"
export KARAF_DATA="${OPENHAB_HOME}/userdata"
export KARAF_BASE="${OPENHAB_HOME}/userdata"
export KARAF_ETC="${OPENHAB_HOME}/runtime/karaf/etc"
```
One problem with putting these entries into the start.sh is that this layout is ignored in case you directly use the Karaf scripts, which I would not forbid to do. So I wonder if it wouldn't be better to put these exports in `karaf/bin/setenv` instead (where there are already comments to do so).

**Comment by maggu2810** [comment]
Still to do the deploy / addons folder...

* Used your folder layout suggestion.
* Directly call the Karaf scripts should work
* The layout is defined in the pom file now

But please check again, if you have time...

I cannot check the windows batch files myself (just added the lines / files without testing), perhaps someone could test this.

**Comment by kaikreuzer** [comment]
Looks good! Only thing I noticed is that there still is a `userdata/data/tmp` folder, which should instead be `userdata/tmp` only.
Another question: Would it be possible to use a variable (like '${openhab.userdata}') instead of the hardcoded "userdata" within the configuration files/scripts? If not set externally, the `setenv` could then set it to the default "userdata". But using a variable would allow people to move the userdata folder to a different file system or partition. Same thing probably makes sense for the "conf" folder. If it is a bigger change, you can leave it for now, it is nothing urgent.

**Comment by maggu2810** [comment]
> Another question: Would it be possible to use a variable (like '${openhab.userdata}') instead of the hardcoded "userdata" within the configuration files/scripts? If not set externally, the setenv could then set it to the default "userdata". But using a variable would allow people to move the userdata folder to a different file system or partition. Same thing probably makes sense for the "conf" folder. If it is a bigger change, you can leave it for now, it is nothing urgent.

Sure, that is possible.
Now it is the same procedure as for the current openHAB 2 runtime. Move the directory and change the value of smarthome.userdata. Do not know, why we should introduce openhab2.userdata if there is smarthome.userdata already. We could set smarthome.userdata to openhab2.userdata and so one. But let's discuss that later, as openhab2.userdata does not exist at the moment.

Perhaps there is some hardcoded stuff in Karaf.
The layout of Karaf is
* / = KARAF_BASE = KARAF_HOME
* /data = KARAF_DATA

Perhaps some code line is using ${karaf.base}/data/tmp instead of ${karaf.data}/tmp.
As long as userdata/data is not set in any environment variable (by me), it is a bug of Karaf that should reported upstream.

**Comment by maggu2810** [comment]
'userdata/data/tmp'... Ah, sorry, that is a remnant of the assembly themselves. Will stop copy it.

**Comment by maggu2810** [comment]
fixed 'userdata/data/tmp'

**Comment by kaikreuzer** [comment]
> Now it is the same procedure as for the current openHAB 2 runtime. Move the directory and change the value of smarthome.userdata.

Are you sure? I doubt that this works, since you configure Karaf nonetheless to use ./userdata: https://github.com/maggu2810/openhab2/blob/master-for-karaf/distributions/openhab2-runtime/pom.xml#L22

> why we should introduce openhab2.userdata if there is smarthome.userdata already

I suggested to introduce "openhab.userdata" :-). Simply because this name is more obvious for openHAB users; the smarthome.userdata is anyhow only an environment variable of Eclipse SmartHome which is meant to be set by the solutions. So openHAB 2 could set it to smarthome.userdata=${openhab.userdata}.

**Comment by maggu2810** [comment]
> Karaf deploy directory should be changed to '${openhab.home}/addons'

https://github.com/openhab/openhab2/issues/386#issuecomment-141499161
> we also won't build an addons.zip - hence there is nothing to put into the addons folder
> And sticking to the addons would defeat the whole sense of switching to Karaf and maintaining Karaf features for all the addons.

Perhaps we should drop the delpoy / addons folder completely in the "new" runtime distribution.
For existing bundles there are Karaf features.
For the developers they should be fine using "bundle:install file:/..."

Should you kept that (the deploying using fileinstall dir) legacy stuff in the Karaf based runtime distribution?

**Comment by kaikreuzer** [comment]
> For the developers they should be fine using "bundle:install file:/..."

Still, it is much simpler to drop stuff into addons. So I would like to keep it at least for a while, as long as we do not yet have everything as Karaf features, because e.g. people still need to test OH1 addons against OH2.

**Comment by maggu2810** [comment]
FYI I think I will have a look at openhab.runtime, openhab.userdata,... next week. Just to see if I am able to solve it :)

**Comment by maggu2810** [comment]
All done except addons directory for fileinstall.

**Comment by kaikreuzer** [comment]
FYI, I have set up an automatic build here: https://openhab.ci.cloudbees.com/job/openHAB2-Karaf/
