### ISSUE TITLE
Items not updated properly in Paper UI

### ISSUE THREAD

**Issue by FallenRiteMonk** [openhab/openhab2#380]
I'm not sure if this belongs here or in the PaperUI repo, but if it does, just tell me and I'll move it!!!!!!!

If i have a item defined in my configs (conf/test.items), launch openHAB, then change the display label of the item in the config and reload the page, I have a second item with the new label.

For example using the network binding and having following item config:
```
Group Network 		"Network"	[ "home-group" ]
Number	D1_Time	"Time"	(Network)	{ channel="network:device:10_90_5_108:time" }
```

and then change the label of D1_Time to "D1 Time", reloading the page in the browser results in having two items displayed ("Time" and "D1 Time" labeled) with values of both items being updated as it should be.

**Comment by kaikreuzer** [comment]
Thanks for reporting this issue. I just analyzed it and it seems to be a bug in the Eclipse SmartHome core, since the REST API returns:
```
{
  "members": [
    {
      "link": "http://localhost:8080/rest/items/D1_Time",
      "state": "NULL",
      "type": "NumberItem",
      "name": "D1_Time",
      "label": "Time",
      "tags": [],
      "groupNames": [
        "Network"
      ]
    },
    {
      "link": "http://localhost:8080/rest/items/D1_Time",
      "state": "NULL",
      "type": "NumberItem",
      "name": "D1_Time",
      "label": "Time D1",
      "tags": [],
      "groupNames": [
        "Network"
      ]
    }
```
May I therefore ask you to enter the issue at https://bugs.eclipse.org/bugs/buglist.cgi?product=SmartHome? Thanks!

**Comment by FallenRiteMonk** [comment]
Reported as you wanted. I also referenced to this issue.
Here the ticket: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477529
