### ISSUE TITLE
Habdroid not loading sitemaps

### ISSUE THREAD

**Issue by sidaga** [openhab/openhab2#381]
Hi,

I am running openhab on a windows 8.1 tablet, habdroid is able to discover sitemaps but as soon as I lock the tablet or it get autolocked for power saving openhab stops responding ... although tablet is connected to wifi as I am able to ping tablet's ip address.
 
Also, I noticed that sitemap discovery is not working if team viewer is installed on the tablet.

Thanks and regards
Siddhartha

**Comment by kaikreuzer** [comment]
As this seems to be a HABDroid issue, please enter it at https://github.com/openhab/openhab.android/issues, thanks.

**Comment by sidaga** [comment]
I figured out that its my tablet only that is losing wifi connectivity in sleep mode.
