### ISSUE TITLE
Use logback instead of log4j

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#384]
Karaf comes with log4j, while openHAB 2 so far uses Logback as a logging implementation.
Sticking to logback might have some benefits, e.g. people are used to configure logging in logback.xml already. Furthermore it has many improvements over log4j and is regarded as the official successor, see http://logback.qos.ch/reasonsToSwitch.html.

According to http://stackoverflow.com/a/32218610, it should be possible to replace log4j with logback.

**Comment by maggu2810** [comment]
I fear, we will loose all the "log:..." commands.

**Comment by kaikreuzer** [comment]
Are you sure?
I would have hoped that log:set is the only command that is not supported (as of https://issues.apache.org/jira/browse/KARAF-3358).

**Comment by maggu2810** [comment]
No, I am not sure. I just want to remind you to consider the log commands, too.

**Comment by ANierbeck** [comment]
As long as you make sure you use an abstraction like slf4j on top of either log4j or logback it shouldn't make much of a difference. Especially since the configuration with the "old" log4j style is much simpler and osgi-friendly then a xml

**Comment by kaikreuzer** [comment]
So you are claiming that [the reasons to use logback](http://logback.qos.ch/reasonsToSwitch.html) by the authors themselves are not valid?

And my other point is again the backward compatibility: If people already have their customized logback.xml from openHAB 1, they should be able to continue to use it.

**Comment by ANierbeck** [comment]
Let me answer in reverse order :-)

using logback.xml ... that's the beauty of Pax Logging, you are free to use, it might require a little re-configuration but it's an alternative solution. 

I'm not saying to not use logback, but there has been a lot of improvements in Pax-Logging for appenders regarding speed and footprint too. Just on top of Log4j, the interesting thing about using the "old" log4j properties syntax is that it plays nicely with configuration admin, while the xml is just another xml that needs extra parsing.

**Comment by kaikreuzer** [comment]
> using logback.xml ... that's the beauty of Pax Logging, you are free to use, it might require a little re-configuration but it's an alternative solution.

Does this mean we could use logback.xml even when staying with log4j?

> there has been a lot of improvements in Pax-Logging for appenders regarding speed and footprint too

Ok, so Pax-Logging is much more than a delegation layer to log4j, but it also addresses shortcomings of it without changing its code?

> "old" log4j properties syntax is that it plays nicely with configuration admin

Yes, that's indeed a very interesting point especially for OSGi-based applications.

**Comment by ANierbeck** [comment]
You can use logback/slf4j api but keep the internal log4j logger in it. Pax Logging has been created long time ago, when logback didn't even exist. Afaik Niclas who wrote it at the time, did have discussion with Ceki at the time on how to better modularize log4j. The result of this is logback ... the only downside is the xml ;) 

Certain shortcomings of log4j have been fixed here and there ... you'd need to check the code for details.

**Comment by kaikreuzer** [comment]
> You can use logback/slf4j api but keep the internal log4j logger in it.

That is clear. I meant can you use slf4j/log4j in Karaf, but configure it with a logback.xml (just as an option to offer for backward compatibility). I would assume the answer is no, correct?

> the only downside is the xml

Well, there is also Groovy as an option. :-)
But I guess that the changed configuration format is the reason that pax-logging never migrated from log4j to logback?

**Comment by ANierbeck** [comment]
you can switch between the following impls: 
- pax-logging-service
- pax-logging-log4j2
- pax-logging-logback

but need to make sure you have the right key set in the pax-logging configuration

org.ops4j.pax.logging.*.config.file

**Comment by kaikreuzer** [comment]
Ok, I gave in to @ANierbeck's arguments and am fine with staying with log4j (for now) - I have created https://github.com/openhab/openhab2/pull/465 in order to adapt the logging to resemble to what we currently have in openHAB.
