### ISSUE TITLE
Introduce addons.cfg file for addon selection

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#385]
The Karaf distribution needs an easy way to define, what addons should be installed, since we won't deliver an addons.zip anymore (since all addons will be shipped with the runtime, but not be pre-installed in it).
As a simple solution for a start, I would suggest a addons.cfg file, which lists all addons (each a single line) with a "#" in front, so that they are commented out by default. The user can then simply remove the # to indicate that the addon should be installed. OH2 would then read this file and install the Karaf features automatically, if they are not yet present.

**Comment by maggu2810** [comment]
> since all addons will be shipped with the runtime, but not be pre-installed in it

Do you really want to pack all install-able addons in the runtime zip?
There are multiple was to do this. We could use kar files, we could fetch the bundles (if requested) automatically from the maven repo, ...
I (as a user) would prefer to have a small runtime zip and is I call "feature:install ..." the necessary bundles are downloaded...
A distributor (e.g. offline distribution) he can create a custom distribution themselves.

If every addon is a feature, the features that should be installed could already be configured in the karaf configuration files.
We could also add a "addon" that reads a file and call feature install for that, but why not using the karaf mechanism as it is already implemented?

**Comment by kaikreuzer** [comment]
> Do you really want to pack all install-able addons in the runtime zip?

Yes, as a first solution. It is what you did right now, isn't it? And it is what people currently do as well, they download both, the runtime and the addons and then choose the addons they want to use.

Doing remote provisioning etc. is something we can imho safely do later on (i.e. after merging).

**Comment by kaikreuzer** [comment]
I have started the implementation here: https://github.com/kaikreuzer/openhab2/commit/6c9c523e07fc25b520c78762a8ce0bb92875f8f6

**Comment by maggu2810** [comment]
Why using uninstall configuration?
I would prefer 
* building a set containing all the installed features (names) starting with openhab-addon-
* building a set of all openhab-addon features that should be installed (by config)
* uninstall stuff in installed but not in configured
* install stuff in configured but not in installed

what do you think about?

**Comment by kaikreuzer** [comment]
> uninstall stuff in installed but not in configured

This is the part that I tend to find a bit risky. It means that this config files is the ONLY place that defines what should be installed or not. So you would not be able to install an addon from the shell, since it will be removed by this logic again on the next start.

Furthermore, I am just adding a servlet, through which UIs have the chance to install and uninstall features as well.

We could also say that the addons.cfg simply only support installing features and removing could be done by the user on the shell. But then again, the "uninstall" option does not really harm, does it?

**Comment by maggu2810** [comment]
I just read your commit and do not really understand the uninstall
configuration parameter. If I configure what should be uninstalled (who
install it?) I thought the file should contol it (perhaps).

> This is the part that I tend to find a bit risky. It means that this
config files is the ONLY place that defines what should be installed or
not. So you would not be able to install an addon from the shell, since it
will be removed by this logic again on the next start.

If you could implement that a manual feature:install (regardless if
triggered by console or web UI), will add the feature to that file and an
uninstall remove it from the file, all would be fine.

Then you have a file that contains all the feature that should currently be
installed (and only that one).

**Comment by maggu2810** [comment]
But I still think it is not needed at all :)

**Comment by kaikreuzer** [comment]
> Then you have a file that contains all the feature that should currently be
installed (and only that one).

Which means that it would have to be always in a writable filesystem, i.e. userdata and not conf.

> But I still think it is not needed at all :)

The uninstall or both? I'd be fine with removing the uninstall, but the install should be an easy first start (but you do not have to use it of course)

**Comment by kaikreuzer** [comment]
I have created https://github.com/maggu2810/openhab2/pull/2 for this. I replaced the "install" key, by keys "binding", "action", etc., I think this makes sense as it structures the file a bit and does not require anymore to put "binding" as a prefix on every single entry.

Furthermore I have implemented a REST endpoint, which can later be used to offer a UI for addon administration.
