### ISSUE TITLE
openhab build error

### ISSUE THREAD

**Issue by gopithulasinathant** [openhab/openhab2#387]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.dependencies.feature.feature.group 2.0.0.qualifier
[ERROR]   Missing requirement: org.openhab.dependencies.feature.feature.group 2.0.0.qualifier requires 'org.eclipse.smarthome.core.library 0.0.0' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab:org.openhab.dependencies.feature:2.0.0-SNAPSHOT @ C:\office\openhab2-2.0.0-alpha2\features\org.openhab.dependencies.feature\pom.xml: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

but I can see my jar in that particular location

**Comment by kaikreuzer** [comment]
Please update your sourcecode, the dependency to org.eclipse.smarthome.core.library had already been removed on July 3: https://github.com/openhab/openhab2/commit/cf49c34c207edb270114451bf5bf259a092bfc3c#diff-f9af89eb8661468f68653fbfd2bb7356

**Comment by gopithulasinathant** [comment]
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.dependencies.feature.feature.group 2.0.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.io.transport.mqtt 0.8.0.201509180447 requires 'package org.eclipse.paho.client.mqttv3 0.0.0' but it could not be found
[ERROR]   Missing requirement: org.eclipse.smarthome.io.transport.mqtt 0.8.0.201509181342 requires 'package org.eclipse.paho.client.mqttv3 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.openhab.dependencies.feature.feature.group 2.0.0.qualifier depends on: org.eclipse.smarthome.io.transport.mqtt 0.0.0
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.openhab:org.openhab.dependencies.feature:2.0.0-SNAPSHOT @ C:\office\openhab2-2.0.0-alpha2\features\org.openhab.dependencies.feature\pom.xml: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by kaikreuzer** [comment]
Please pull my latest commit and try again - I hope it fixes the problem!

**Comment by gopithulasinathant** [comment]
Thanks a lot working well with a  new update

**Comment by kaikreuzer** [comment]
Glad to hear!
