### ISSUE TITLE
Fibaro FGS221 2x1,5kW can't configure device index 14 ( set bi-switch to monoswitch)

### ISSUE THREAD

**Issue by Philippwolf** [openhab/openhab2#390]
I'm using openhab 2 with habmin2 and the zwave 1.8 binding and everything is working so far, i only have 1 problem : i have no way of configuring value 14 in order to set the switch to mono, in habmin device configuration it shows up with no value and no way to edit it, any hints on how to proceed?
I already tried editing the userdata/zwave/node.xml with the right value (0), to no avail though, after refreshing the device configuration the setting jumped back to 1 :( and my light still instantly turns off once i let go of the physical mono switch.

kind regards!

/e managed to do it using openhab1, but why?

**Comment by kaikreuzer** [comment]
@cdjackson Did you see this issue?

**Comment by cdjackson** [comment]
Nope - missed it, sorry. I'm tempted to say if it works in oh1 then it's not a problem with the binding and close it until the oh2 binding is released.

**Comment by kaikreuzer** [comment]
ok, so let's close as won't fix and wait for the new binding!
