### ISSUE TITLE
Hitting a lot of Missing Constraint Errors with the Latest IDE Installation

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#391]
Hi,

I reinstall OH2 IDE and hits with many plugin dependency issues although i never tick any addons. When i navigate to Run/Debug Configurations->openHAB_Runtime->Plugins->Validate Plugins, i see the following errors. Obviously, when i checked on the plugin list, i couldn't find those missing bundles. How do manually force eclipse to pull those dependencies? Thanks

![error](https://cloud.githubusercontent.com/assets/13405324/9979262/69a4a966-5f96-11e5-8566-145bb2278f77.png)

**Comment by lsafelix75** [comment]
UPDATE:  During Eclipse installation, if i select "OpenHAB 2 with Eclipse SmartHome Core" instead of "OpenHAB 2 Development", then it solves all the dependencies error.

![error1](https://cloud.githubusercontent.com/assets/13405324/9981242/45ece7c8-5fea-11e5-8e94-9edf05c5bd31.png)

**Comment by lsafelix75** [comment]
UPDATE: I resolve this after i run Help->"Perform Setup Tasks" again after IDE completed the setup tasks.

**Comment by kaikreuzer** [comment]
Cool, glad you were able to figure it out before I found the time trying to reproduce the problem :-)

**Comment by kaikreuzer** [comment]
This is actually a bug in the current Oomph setup profile - will fix it!

**Comment by kaikreuzer** [comment]
Now it should be REALLY fixed, so that it is not necessary anymore to run the setup tasks manually.
