### ISSUE TITLE
icons problem

### ISSUE THREAD

**Issue by haydarali** [openhab/openhab2#393]
Hi,
OH 2.0.0 using start and no problem control, but icons do not appear on the web browser and mobile app. icons folder in "runtime/icons"
![icons](https://cloud.githubusercontent.com/assets/13448487/10042072/aad356dc-61f1-11e5-8d1b-4940b88c6063.jpg)

**Comment by kaikreuzer** [comment]
The folder runtime/icons does not exist anymore. Are you sure you are using the latest snapshot?

**Comment by haydarali** [comment]
Yes, I downloaded yesterday. Folder icons I added later.

**Comment by kaikreuzer** [comment]
So you mean you do not use the standard icons but have changed your sitemap to reference custom ones?
Custom icons have to go into conf/icons/classic. Then they should be picked up correctly.

**Comment by haydarali** [comment]
I had the same problem in the previous version are corrected so I waited. Yesterday I tried to download again, but the result is still the same. That's why I'm using alpha-2.

**Comment by kaikreuzer** [comment]
I have just checked again on the latest snapshot. All works well, if you put your custom icons in `${openhab.home}/conf/icons/classic`.

**Comment by haydarali** [comment]
Yes, it works. The web interface works fine. But the mobile application items do not change icon to status. Only constant.

**Comment by haydarali** [comment]
Yes, it works. The web interface works fine. But the mobile application items icon do not change icon of status. Only constant.

**Comment by haydarali** [comment]
I wrote the above problems, it continues in the latest snapshot. I manually installing the icons folder (Openhab.ho to $ {} / conf / icons / classic) and great, icons web page looks and works fine. But the mobile application icons looks stable. Icons do not change according to the item status.

![image](https://cloud.githubusercontent.com/assets/13448487/11429722/c99460fa-9484-11e5-8a1b-dd3ba40a5e64.png)
OpenHAB running tested on windows and raspberry pi2
java 1.7.0.79 and 1.8

**Comment by kaikreuzer** [comment]
I can confirm, I will have to investigate this in more depth. I assume that this might need a change in the mobile apps.

**Comment by haydarali** [comment]
Latest snapshot not need manuel icons folder create. Direct seeing all icons. But icons not change of status on mobile application. When do you plan to change the mobile applications?

**Comment by kaikreuzer** [comment]
I have entered
https://github.com/openhab/openhab.android/issues/145 and
https://github.com/openhab/openhab.ios/issues/65

If you are fluent in iOS or Android programming, feel free to provide a PR yourself!
