### ISSUE TITLE
Homematic Binding

### ISSUE THREAD

**Issue by patrickse** [openhab/openhab2#398]
I´ve just tested the homematic binding and it looks quite good. I will try to replace my current openhab setup with openhab 2. I got one suggestion, may be it possible to reduce the amount of default channels to just the sane ones. 

For example, just show:
- set temperature
- actual temperature

for the valve drives.

Just an idea.. 
Patrick

**Comment by Jochen1980** [comment]
Where can I download the homematic binding?

**Comment by patrickse** [comment]
Take a look at #88. There are few hints, how to get it running.

**Comment by patrickse** [comment]
@gerrieg

**Comment by gerrieg** [comment]
That's possible, but we need to find a logic to identify the sane ones. I don't like to implement this logic device based. Currently the logis for the advanced channels is:

- all from channel 0
- channel 18 from 19 button remote control
- INSTALL_TEST datapoint
- all channels from MASTER paramset

everything else is default.

Do you have any idea how to identify the sane ones? Remember, this binding is not only for Homematic, but also for Homegear which has growing device families (MAX, Insteon, Hue and soon more)

**Comment by kaikreuzer** [comment]
Please move discussions to https://community.openhab.org/c/openhab-2/bindings and don't use the issue tracker for that!
