### ISSUE TITLE
Karaf installs cfg files in userdata instead of conf

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#401]
When installing a feature that comes with a config file, Karaf installs that file in `userdata/conf/services/` while it should be in `conf/services/` instead.
I am aware that conf is not necessarily meant to be readable, but this is the constraint we have to accept; after all, the files are only meant as a starting point to help the user on the configuration.

**Comment by maggu2810** [comment]
I guess it is using "${karaf.base}" as reference.
Let's try to set "${openhab.conf}/services" as the location directory.

2015-09-30 22:24 GMT+02:00 Kai Kreuzer <notifications@github.com>:

**Comment by maggu2810** [comment]
https://issues.apache.org/jira/browse/KARAF-3262

**Comment by kaikreuzer** [comment]
Hm, does this mean we cannot solve the issue or is there some workaround...?

**Comment by maggu2810** [comment]
This does mean we have to create a PR for Karaf. :wink:

**Comment by kaikreuzer** [comment]
There is actually a VERY simple workaround for this: We can simply add a ../ in the target location for the config files in the feature.xml. I've just tested this and it seems to work nicely :-)

**Comment by maggu2810** [comment]
I know. But I do all the oh2_dir_layout changes, because you want to be able to move conf etc.
I already added a PR and will wait if it could be included in 4.0.2.

Don't like to add such a workaround if the PR is accepted. Let's wait a little bit.
Okay?

**Comment by maggu2810** [comment]
BTW the relative location between karaf.base and openhab.conf differs between openhab2-runtime-karaf and openhab2-runtime.
So this could be solved (using the workaround) only for one of them and break the other one.

**Comment by maggu2810** [comment]
FYI: The problem for me is not to break openhab2-runtime-karaf and support openhab2-runtime. The problem is, that using ../ in front of the final name, we use a directory in top of karaf.base. This will write outside of the distribution if karaf.base is the top karaf directory.

**Comment by kaikreuzer** [comment]
You are right that it is a very ugly workaround that would only make openhab2-runtime work under the precondition that the user did not move conf nor userdata to a different location. So indeed this should only be considered as a short-term and temporary solution. Having your PR accepted for 4.0.2 is definitely the MUCH better way!

**Comment by maggu2810** [comment]
> Having your PR accepted for 4.0.2 is definitely the MUCH better way!

merged: https://github.com/apache/karaf/pull/83

**Comment by maggu2810** [comment]
Solved by #417 + #424

**Comment by kaikreuzer** [comment]
Great, thanks!
