### ISSUE TITLE
Maven : missing requirements on org.eclipse.smarthome.io.transport.mdns 0.8.0.201509250706

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#405]
see the logs below, right after a pull from the master repo 

Karel-Goderis-MacBook-Air:openhab2 kgoderis$ mvn clean install
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.astro:2.0.0-SNAPSHOT @ /Users/kgoderis/openhab2-master/git/openhab2/addons/binding/org.openhab.binding.astro/pom.xml
[INFO] Adding repository http://download.eclipse.org/smarthome/updates-stable
[INFO] Adding repository https://openhab.ci.cloudbees.com/job/smarthome/lastSuccessfulBuild/artifact/products/org.eclipse.smarthome.repo/target/repository
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201502271000/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/luna/201502271000
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
[INFO] Fetching p2.index from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201407030533/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201407030533
[INFO] Adding repository http://dist.springsource.org/release/GRECLIPSE/e4.4
[INFO] Adding repository http://www.openhab.org/jupnp/update-site
[INFO] Adding repository http://hstaudacher.github.io/osgi-jax-rs-connector/5.0.0
[INFO] Adding repository http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.12.v20150709
[INFO] Adding repository https://github.com/openhab/openhab.repo/raw/master/jetty-deps
[INFO] Fetching content.jar from https://github.com/openhab/openhab.repo/raw/master/jetty-deps/ (0B of 1.39kB at 0B/s)
[INFO] Adding repository http://download.eclipse.org/paho
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.smarthome.feature.runtime.core.feature.group 0.8.0.201509250706
[ERROR]   Missing requirement: org.eclipse.smarthome.io.transport.mdns 0.8.0.201509250706 requires 'package javax.jmdns 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.feature.runtime.core.feature.group 0.8.0.201509250706 depends on: org.eclipse.smarthome.io.transport.mdns [0.8.0.201509250706]
[ERROR] 
[ERROR] Failed to resolve target definition /Users/kgoderis/openhab2-master/git/openhab2/targetplatform/openhab.target: See log for details -> [Help 1]

**Comment by kaikreuzer** [comment]
Hm, this is weird, I get
```
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.astro:2.0.0-SNAPSHOT @ /Users/kai/openhab2-master4/git/openhab2/addons/binding/org.openhab.binding.astro/pom.xml
[INFO] Adding repository http://download.eclipse.org/smarthome/updates-stable
[INFO] Adding repository https://openhab.ci.cloudbees.com/job/smarthome/lastSuccessfulBuild/artifact/products/org.eclipse.smarthome.repo/target/repository
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201502271000/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/luna/201502271000
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
[INFO] Fetching p2.index from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201407030533/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201407030533
[INFO] Adding repository http://dist.springsource.org/release/GRECLIPSE/e4.4
[INFO] Adding repository http://www.openhab.org/jupnp/update-site
[INFO] Adding repository http://hstaudacher.github.io/osgi-jax-rs-connector/5.0.0
[INFO] Adding repository http://download.eclipse.org/jetty/updates/jetty-bundles-9.x/9.2.12.v20150709
[INFO] Adding repository https://github.com/openhab/openhab.repo/raw/master/jetty-deps
[INFO] Fetching content.jar from https://github.com/openhab/openhab.repo/raw/master/jetty-deps/ (0B of 1.39kB at 0B/s)
[INFO] Adding repository http://download.eclipse.org/paho
[INFO] Adding repository http://www.openhab.org/jmdns/update-site/3.4.2
```
Note the very last line - this is where javax.jmdns resides. This repo is missing for some reason in your log.
Can you confirm that the openhab.target file lists it?

**Comment by kgoderis** [comment]
I will have to check, but I never touch these files anymore since oomph, and still, from time to time it completely fails for some reason. I always failed to understand why that it. Is it Eclipse IDE caching? Stuff goes missing for some reason and so forth.

**Comment by kgoderis** [comment]
Do you reckon that these kind of problems stem from the fact that I share the IDE between my smarthome and openhab repo's e.g. conflicts in caching etc? Is is typically when I switch between both instances (and I only do this every so much time), that I run in these kinds of problems. I have now copied over openhab.target manually from github in order to resolve it

**Comment by kaikreuzer** [comment]
>  I have now copied over openhab.target manually from github in order to resolve it

Does this mean that there was any difference in the files you had locally to the one from github or why could this possible resolve the problems...? So are they really resolved for you now? If so, please close the issue.

**Comment by kirantpatil** [comment]
I am also facing the same issue while building using https://github.com/openhab/openhab2/blob/master/docs/sources/development/ide.md

![screenshot from 2015-10-05 19-02-30](https://cloud.githubusercontent.com/assets/1178055/10281659/ac3ee828-6b93-11e5-9af5-be95536f8672.png)

![screenshot from 2015-10-05 19-03-29](https://cloud.githubusercontent.com/assets/1178055/10281671/cd550132-6b93-11e5-9bb7-f3eecccad0cd.png)

**Comment by kaikreuzer** [comment]
@kirantpatil No, in your case it is merely the launch configuration which does not include this bundle.
I have added it to the launch config with https://github.com/openhab/openhab2/commit/25bf2fe33ac425462e065bbe6146a290d8a88bf6, so this should solve the issue for you.
