### ISSUE TITLE
SLF4J: The following loggers will not work because they were created during the default configuration phase 

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab2#409]
I am facing the below issue while building using https://github.com/openhab/openhab2/blob/master/docs/sources/development/ide.md

Java version: jdk1.8.0_60
OS: Fedora 22, x86_64

![screenshot from 2015-10-06 12-20-54](https://cloud.githubusercontent.com/assets/1178055/10301901/bb3f5952-6c24-11e5-92d6-77c222d10f14.png)

SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.jetty.util.log
SLF4J: org.eclipse.jetty.osgi.boot.JettyBootstrapActivator
SLF4J: org.eclipse.jetty.osgi.boot.internal.serverfactory.JettyServerServiceTracker
SLF4J: org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper
SLF4J: org.eclipse.jetty.osgi.boot.utils.BundleFileLocatorHelperFactory
SLF4J: org.eclipse.jetty.util.resource.Resource
SLF4J: org.eclipse.jetty.util.resource.FileResource
SLF4J: org.eclipse.jetty.osgi.boot.internal.serverfactory.ServerInstanceWrapper
SLF4J: org.eclipse.jetty.xml.XmlConfiguration
SLF4J: org.eclipse.jetty.xml.XmlParser
SLF4J: org.eclipse.jetty.util.TypeUtil
SLF4J: org.eclipse.jetty.util.component.AbstractLifeCycle
SLF4J: org.eclipse.jetty.util.component.ContainerLifeCycle
SLF4J: org.eclipse.jetty.server.handler.AbstractHandler
SLF4J: org.eclipse.jetty.server.Server
SLF4J: org.eclipse.jetty.util.thread.QueuedThreadPool
SLF4J: org.eclipse.jetty.rewrite.handler.RuleContainer
SLF4J: org.eclipse.jetty.server.handler.ContextHandlerCollection
SLF4J: org.eclipse.jetty.server.handler.DefaultHandler
SLF4J: org.eclipse.jetty.util.resource.URLResource
SLF4J: org.eclipse.jetty.util.IO
SLF4J: org.eclipse.jetty.server.handler.RequestLogHandler
SLF4J: org.eclipse.jetty.server.handler.ContextHandler
SLF4J: org.eclipse.jetty.webapp.WebAppContext
SLF4J: org.eclipse.jetty.util.ssl.SslContextFactory
SLF4J: org.eclipse.jetty.util.security.Credential
SLF4J: org.eclipse.jetty.util.security.Password
SLF4J: org.eclipse.jetty.server.SecureRequestCustomizer
2015-10-06 12:15:30 [DEBUG] [s.m.i.r.i.ItemRuntimeActivator:23   ] - Registered 'item' configuration parser
2015-10-06 12:15:30 [INFO ] [uartz.impl.StdSchedulerFactory:1184 ] - Using default implementation for ThreadExecutor
2015-10-06 12:15:30 [INFO ] [rtz.core.SchedulerSignalerImpl:61   ] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2015-10-06 12:15:30 [INFO ] [rg.quartz.core.QuartzScheduler:240  ] - Quartz Scheduler v.2.2.1 created.
2015-10-06 12:15:30 [INFO ] [org.quartz.simpl.RAMJobStore  :155  ] - RAMJobStore initialized.
2015-10-06 12:15:30 [INFO ] [rg.quartz.core.QuartzScheduler:305  ] - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

**Comment by kaikreuzer** [comment]
Just ignore it, this only concerns log messages from Jetty, which are anyhow suppressed as much as possible. It should not have any impact on any other functionality of openHAB.

**Comment by kirantpatil** [comment]
Thanks.
