### ISSUE TITLE
PaperUI Missing Configuration Settings

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#410]
Hi,

Under ESH-INF -> thing -> *.xml, i have the following defined for a channel. As you can see, each channel type has additional parameters to set. However, on PaperUI, I can't seem to find a way to let user to define the following parameters per channel (after discovery process). User can only select what channels to link but not able to configure additional parameters for the selected channels. Cheer. 

   <channel-type id="status">
        <item-type>Switch</item-type>
        <label>Status</label>
        <description>Switch</description>
              <config-description>
            <parameter name="out-transform" type="text" required="false">
                <label>Transformation mapping for output command</label>
                <default></default>
                <description>This refers to deviceID</description>
            </parameter> 
            <parameter name="in-transform" type="text" required="false">
                <label>Transformation mapping for input state</label>
                <default></default>
                <description></description>
            </parameter>            
        </config-description>
    </channel-type>

**Comment by kaikreuzer** [comment]
Please use proper code tags when posting XML or Java code in issues.

The Paper UI does not support configuration of channels. Feel free to add a feature request at https://github.com/openhab/smarthome.paperui/issues.
