### ISSUE TITLE
Set up REST Server in openHAB2

### ISSUE THREAD

**Issue by Steckdoserich** [openhab/openhab2#411]
How can I use the REST interface in openHAB2? I only find informations on how to request the server, but not where to put my own resources or the GET/POST/PUT/DELETE functions.

**Comment by kaikreuzer** [comment]
You can find all available operations on http://demo.openhab.org:9080/doc/index.html.

Please use our community for questions like this: https://community.openhab.org/c/openhab-2

**Comment by Steckdoserich** [comment]
I already looked at the demo, but it only shows to possible methods. How do I implement my own methods? Do I need to make changes in the Eclipse SmartHome namespace? I saw the ThingResources.java, do I have to implement my own functions like that?

**Comment by Steckdoserich** [comment]
I opened two new threads in your community board. Could you please take a look?
https://community.openhab.org/t/setup-ide-for-openhab2/3122
https://community.openhab.org/t/how-to-configure-your-own-rest-interfaces/3121
Thank you in advance
