### ISSUE TITLE
Newly Developed Not Loaded in Distribution Package

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab2#414]
Hi,

I have the following setup. It runs fine with the newly developed test addons on Eclipse. However, when i export the addon to a jar (right click -> Export -> Deployable Plugins and Fragments ->tick "User class files compiled in the workspace) and copy into addons folder of distribution package, and then run start_debug.sh. The "test" addon is not loaded at all. Question is, how do i check whats-wrong? Thanks

Item:
Switch test1    "Switch 1"       (GF_Corridor, Lights) { channel="test:topic:mygateway1:myswitch1:status" }

Things:
Bridge test:broker:mygateway1 [ broker="local", refreshInterval=60] {
   Thing topic myswitch1 [ topic="switch", deviceId="5", switchId="3" ] {
       Switch : status [ subtopic="status", out-transform="MAP(default_out.map)", in-transform="MAP(default_in.map)" ]  
       }
}

**Comment by kaikreuzer** [comment]
This is not a bug report, so please discuss such things in the community at https://community.openhab.org/.
In general, I would advice some OSGi tutorial for a start, this can help immensely when debugging: http://devblog.virtage.com/2012/08/osgi-with-equinox-for-beginners-overview/#basic-osgi-console-commands
