### ISSUE TITLE
Karaf: addons directory

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#415]
This issue continues #379. All is done without:
* Karaf deploy directory should be changed to '${openhab.home}/addons'

**Comment by maggu2810** [comment]
@kaikreuzer Could you add the karaf label?

**Comment by kaikreuzer** [comment]
Yes, if I may also assign it to you ;-)

**Comment by kaikreuzer** [comment]
I have tried adding a `org.apache.felix.fileinstall-deploy.cfg` as described in https://karaf.apache.org/manual/latest/users-guide/deployers.html, but somehow nothing happens.
Do I have to add some feature first in order to make the deployer work?

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/openhab/openhab2/pull/462
