### ISSUE TITLE
Problem with Classic UI and Setpoint of auto discovery things

### ISSUE THREAD

**Issue by patrickse** [openhab/openhab2#428]
Hi,

I am currently testing the new Homematic binding. It looks quite good except one problem with the IOS App/Classic UI. The UI does not offer any control to change the temperature of my valve drives. I though it was problem caused by the iOS app. But it actually works with the app and the openhab2 demo. 

So maybe the problem depends on the auto discovery functionality inside openhab2.

Has anyone experienced problems with the app or classic ui and auto discovered things with a set point feature?

openhab/openhab.ios#48

**Comment by kaikreuzer** [comment]
This rather sounds to me like a question or the start of some analysis. I would suggest to move the discussion to https://community.openhab.org/c/openhab-2 and only open an issue, if a real problem is identified.

**Comment by patrickse** [comment]
Just to close the loop... Here´s the link to the following discussion:
https://community.openhab.org/t/facing-a-problem-with-oh2-ios-classic-ui/3339/4
