### ISSUE TITLE
cleanup: certificate generation

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#430]
I tried to merge the changes to the Karaf branch and have another look at the changes:

* We are using for the path to the keystore file "jetty.keystore.path"
* We are using for the path to the truststore file "jetty.truststore"

IMHO we should use "jetty.truststore.path" to use a similar naming scheme

The following start configuration (excerpt):
* org.openhab.core.compat1x@default:true
* org.openhab.core.init@1:true
* org.openhab.core@5:true
* org.openhab.io.jetty@default:default
* org.openhab.io.rest.docs@default:true

Was changed to:
* org.openhab.core.compat1x@default:true
* org.openhab.io.jetty.certificate@3:default
* org.openhab.core.init@1:true
* org.openhab.core@5:true
* org.openhab.io.jetty.certificate.generator@1:default
* org.openhab.io.jetty@default:default
* org.openhab.io.jetty.certificate.generator@default:default
* org.openhab.io.rest.docs@default:true

I believe the "org.openhab.io.jetty.certificate.generator" lines could be removed.

**Comment by kaikreuzer** [comment]
@Stratehm Could you have a look, please?

**Comment by Stratehm** [comment]
I have also removed the keystore file. Maybe we should add it in gitignore to avoid to commit it.

**Comment by kaikreuzer** [comment]
> I have also removed the keystore file.

You actually had it removed, but I put it back, since otherwise you cannot launch the runtime in the IDE.
I excluded it from the distribution (see https://github.com/openhab/openhab2/blob/master/distribution/src/assemble/runtime.xml#L20) though.

**Comment by Stratehm** [comment]
> You actually had it removed, but I put it back, since otherwise you cannot launch the runtime in the IDE.
I excluded it from the distribution (see https://github.com/openhab/openhab2/blob/master/distribution/src/assemble/runtime.xml#L20) though.

OK. keystore file restored.

**Comment by kaikreuzer** [comment]
@maggu2810, all ok for you?

**Comment by maggu2810** [comment]
All fine, thanks @Stratehm
