### ISSUE TITLE
applied changes required to be compatible with latest stable ESH build

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#431]
Still some stuff missing...

```sh
$ grep -r eclipse.smarthome.core.scriptengine
```
<pre>
./bundles/core/org.openhab.core.compat1x.test/Compat1xTests.launch
./addons/binding/org.openhab.binding.max.test/MaxBindingTests.launch
./addons/io/org.openhab.io.myopenhab/OSGI-INF/myopenhab.xml
./targetplatform/openHAB_with_ESH.launch
./targetplatform/openHAB_Runtime.launch
</pre>

**Comment by kaikreuzer** [comment]
The launch configs are not really relevant as missing bundles will simply be ignored and on the next edit, it will go away.
The xml file is fixed with https://github.com/openhab/openhab2/pull/432, thanks for noticing!
