### ISSUE TITLE
SMA Energy Meter Binding

### ISSUE THREAD

**Issue by monnimeter** [openhab/openhab2#441]
Hi all,
I started implementing a new binding for the SMA Smart Meter (details http://www.sma.de/produkte/monitoring-control/sma-energy-meter.html) and would like to contribute it to the community.
I will appreciate your help and any feedback as I'm a newbe regarding openhab and github and things :)

Thank you and regards,
Osman

**Comment by monnimeter** [comment]
First implementation uploaded. See #443

**Comment by kaikreuzer** [comment]
Implemented and merged, thanks!
