### ISSUE TITLE
OpenHAB2 How to ensure security?

### ISSUE THREAD

**Issue by haydarali** [openhab/openhab2#442]
Hi,

OH2 how to ensure security? I did the following steps, but did not run.

I changed to "org.eclipse.smarthome.security:option=ON" in services.cfg
I added "conf" directory into the "users.cfg" file.
I added "runtime/etc" directory into the "login.conf" file.

login.conf =
*openHAB.org {
	org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
	debug="true"
	file="${jetty.home}/conf/users.cfg";
};*

**Comment by kaikreuzer** [comment]
Authentication is not yet implemented, see https://github.com/openhab/openhab2/blob/master/docs/sources/intro.md#known-limitations

**Comment by haydarali** [comment]
Thanks. Is there any work?

**Comment by kaikreuzer** [comment]
as far as I know, @teichsta wanted to work on this in September. @teichsta, any update on this?
