### ISSUE TITLE
One wire binding

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab2#444]
Please also implement the "one wire" binding in Openhab 2.

**Comment by kaikreuzer** [comment]
Why? Isn't the 1.x 1Wire binding not working? Please only open issues here, if you started some implementation yourself.

**Comment by TheNetStriker** [comment]
I am currently using openremote and am considering to switch to openhab if version 2.0 is released. I didn't find one wire on the compatibility page so I assumed the plugin is not yet working.

**Comment by kaikreuzer** [comment]
I see it listed here: https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md#compatible-1x-add-ons
It should therefore work just fine with openHAB 2 - have a try!

**Comment by TheNetStriker** [comment]
Perfect, thanks and sorry about the circumstances.

**Comment by kaikreuzer** [comment]
No worries, always happy to help!
