### ISSUE TITLE
LightweightM2M / Leshan / IPSO

### ISSUE THREAD

**Issue by mtornblad** [openhab/openhab2#445]
Hello,

I've been playing around a bit with launching the Leshan-server inside Openhab2 to get lwm2m/IPSO objects into OpenHab! I've gotten so far that when a lwm2m client connects to the leshan server it is shown in the paperui inbox. My biggest issue right now before i continue is how i should map the lwm2m objects against the "thing" structure.

From: http://www.ipso-alliance.org/wp-content/media/draft-ipso-app-framework-04.pdf

 An example design of a theoretical plug socket sensor, with two plugs
 (index of 0 and 1) a button and a LED, along with temperature and CO2
 sensors in CoRE Link Format. The following examples make use of this
 resource design.
<code>
 \</dev/mfg\>;rt="ipso.dev.mfg",
 \</dev/ser\>;rt="ipso.dev.ser",
 \</dev/mdl\>;rt="ipso.dev.mod",
 \</pwr/0/w\>;rt="ipso.pwr.w",
 \</pwr/0/kwh\>;rt="ipso.pwr.kwh",
 \</pwr/0/rel\>;rt="ipso.pwr.rel",
 \</pwr/1/w\>;rt="ipso.pwr.w",
 \</pwr/1/kwh\>;rt="ipso.pwr.kwh",
 \</pwr/1/rel\>;rt="ipso.pwr.rel",
 \</gpio/btn/0\>;rt="ipso.gpio.btn",
 \</lt/led0/on\>;rt="ipso.lt.on",
 \</sen/temp\>;rt="ucum.Cel";obs,
 \</sen/co2\>;rt="ucum.ppm"
</code>
What would make most sense from the above sample, try to create one thing and add channels dynamically that maps to the above items, or to make one "thing" per sub device, ie 2 plug-things, 1 button-thing... etc, and in this case, is there a way to group them together?

If you think the dynamic channels is the way to go, how is this made? I tried to test that approach in the handle-class, but just ended up with errors.

//Mattias

**Comment by kaikreuzer** [comment]
Hi Mattias,

That sounds pretty cool and I am definitely interested to get that working with you. Nonetheless, this issue tracker is probably not the best place for such a discussion. Might I therefore ask you to enter your question at https://www.eclipse.org/forums/index.php/f/271/ so we can follow up there? Thanks!

**Comment by kaikreuzer** [comment]
Thanks! FTR: https://www.eclipse.org/forums/index.php?t=rview&goto=1713086#msg_1713086
(Will try to answer soon...)
