### ISSUE TITLE
ESH random behaviour on updateState()

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#45]
This related to Sonos, or the ESH event bus, or auto-approve. Anyways, I am experiencing random behaviour which is hard to replicate. This is what happens:

In the openhab.log : 

11:09:55.852 TRACE o.e.s.i.t.u.UpnpIOServiceImpl[:75]- A GENA subscription 'RenderingControl' for device 'uuid:RINCON_000E58D6F22801400' is established
...
11:09:56.128 TRACE o.o.b.s.h.ZonePlayerHandler[:294]- Received pair 'VolumeMaster':'50' (service 'RenderingControl') for thing 'sonos:zoneplayer:RINCON_000E58D6F22801400'
11:09:56.128 DEBUG o.o.b.s.h.ZonePlayerHandler[:381]- Updating Volume of ZPH 'sonos:zoneplayer:RINCON_000E58D6F22801400' to '50'

which is generated by the following code block:

		case "VolumeMaster": {
			logger.debug("Updating Volume of ZPH '{}' to '{}'",this.getThing().getUID(),new PercentType(stateMap.get("VolumeMaster")));
			updateState(new ChannelUID(getThing().getUID(), VOLUME),
					(stateMap.get("VolumeMaster") != null) ? new PercentType(
							stateMap.get("VolumeMaster")) : UnDefType.UNDEF);
			break;

but, in events.log we have the following:

2014-11-15 11:10:55 - sonos_zoneplayer_RINCON_000E58D6F22801400_zonename state updated to Bedroom Georges
2014-11-15 11:10:55 - sonos_zoneplayer_RINCON_000E58D6F22801400_zonegroup state updated to Undefined
2014-11-15 11:10:55 - sonos_zoneplayer_RINCON_000E58D6F22801400_alarmproperties state updated to No running alarm
2014-11-15 11:10:55 - sonos_zoneplayer_RINCON_000E58D6F22801400_led state updated to ON

and in the console we have:

osgi> smarthome items sonos_zoneplayer_RINCON_000E58D6F22801400*
...
sonos_zoneplayer_RINCON_000E58D6F22801400_zonename (Type=StringItem, State=Bedroom Georges)
....
sonos_zoneplayer_RINCON_000E58D6F22801400_volume (Type=DimmerItem, State=Uninitialized)

So:
1. updateState() call does not generate event in events.log. Item not yet created? timing issue?
2. Item does exist in console, but not defined yet
3. issuing a "smarthome item send ... INCREASE" to an uninitialised Item does update the value

**Comment by kaikreuzer** [comment]
The whole lifecycle has been massively changed with the latest ESH stable release that is now available to openHAB 2. I would assume that this issue does not exist anymore. Please feel free to reopen this issue in case that my assumption is wrong!
