### ISSUE TITLE
Rename features

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#451]
I would like to propose a simplification of the naming of the Karaf features:
Instead of openhab2-addon, I would only want to use the prefix "openhab-". This means that instead of
```
openhab2-addon-action-mail
openhab2-addon-binding-anel
openhab2-addon-transport-mqtt
```
we would have
```
openhab-action-mail
openhab-binding-anel
openhab-transport-mqtt
```
At the same time, we should fill out the "description" with a label that can be used in a UI, e.g. "Mail Action" or "Anel Binding".

@maggu2810 Is that ok for you?

**Comment by maggu2810** [comment]
This is ok for me
