### ISSUE TITLE
timer.reschedule doesn't restart timer

### ISSUE THREAD

**Issue by TeraHz** [openhab/openhab2#454]
I was just writing my first timer following the guides and it looks like the reschedule() method doesn't trigger a new run of the timer. 
```
var Timer timer = null
rule "Garage lights off"
...
       if (timer==null){
                // first motion detected
                logInfo("GARAGE","Starting timer before turning off the lights")
                timer = createTimer(now.plusSeconds(5)) [|
                                logInfo("GARAGE","Turning lights off")]
        }else{ 
                logInfo("GARAGE", "We have a timer already, reenabling")
                timer.reschedule(now.plusSeconds(5))
                if (timer.isRunning()){
                        logInfo("GARAGE", "RUNNING")
                }else{
                        logInfo("GARAGE", "NOT RUNNING")
                }
        }
```

In the above code, the first time around, the timer is null, so things are created properly and after 5 seconds I see the lights off message. Second come around, the timer is not null, hasTerminated() returns true (removed for brevity) , but after the timer.reschedule() call, it is still not running. 

Here is the log output from the above code:

```
2015-11-01 01:57:54.295 [INFO ] [.smarthome.model.script.GARAGE] - Starting timer before turning off the lights
2015-11-01 01:57:59.297 [INFO ] [.smarthome.model.script.GARAGE] - Turning lights off
2015-11-01 01:58:22.104 [INFO ] [.smarthome.model.script.GARAGE] - We have a timer already, reenabling
2015-11-01 01:58:22.105 [INFO ] [.smarthome.model.script.GARAGE] - NOT RUNNING
```

Any ideas? Am I doing something wrong or is this a known issue?

**Comment by kaikreuzer** [comment]
reschedule only works if the timer is still scheduled (i.e. not yet executed). Your rule should work as expected if you change it to
```
var Timer timer = null

rule "Garage lights off"
   when ...
   then
       if (timer==null) {
                // motion detected
                logInfo("GARAGE","Starting timer for turning off the lights")
                timer = createTimer(now.plusSeconds(5)) [|
                                logInfo("GARAGE","Turning lights off")
                                timer = null ]
        } else { 
                logInfo("GARAGE", "We have a timer already, rescheduling")
                timer.reschedule(now.plusSeconds(5))
        }
end
```

**Comment by Taudris** [comment]
If this issue is not going to be solved, can the docs be updated to reflect the actual behavior?

[https://github.com/openhab/openhab/wiki/Actions#timers](https://github.com/openhab/openhab/wiki/Actions#timers)

**Comment by kaikreuzer** [comment]
@Taudris If you feel that the openHAB 1 wiki is not correct or needs to be enhanced, feel free to change it.

**Comment by cHynInTeam** [comment]
One more place, to be fixed:
`package org.eclipse.smarthome.model.script.actions;
public interface Timer {
    /**
     * Reschedules a timer to a new starting time.
     * This can also be called after a timer has terminated, which will result in another
     * execution of the same code.
     * 
     * @param newTime the new time to execute the code
     * @return true, if the rescheduling was done successful
     */
    public boolean reschedule(AbstractInstant newTime);
}`

Description in this interface is wrong.
