### ISSUE TITLE
Osram Lightify PAR16 50 Tunable White

### ISSUE THREAD

**Issue by markusmazurczak** [openhab/openhab2#456]
Hi all,

I am using Osram Lightify PAR16 50 Tunable White bulbs (GU10 bulb fitting) connected using an Hue bridge.
The first thing I discovered was that they are not auto-discovered.
The second thing was, that they cannot be powered off and on correctly.

By now I managed to create a new thing XML and added the bulbs as an supported thing type (auto-discover works after that).

The second thing I am currently working on is that powering issue.
If I set the state for such a bulb to OFF then the bulb is just dimmed down but never powered off really. After that it is not possible to turn them ON again.
I found an workaround for that doing the following:

1) Powering off a bulb
I added `setTransitionTime(0)`

`stateUpdate.setOn(false);
 stateUpdate.setTransitionTime(0);`

2) Powering on a bulb
I added `setBrightness(254)`

`stateUpdate.setOn(true);
            stateUpdate.setBrightness(254);`

By now I've just done a quick fix for me. This means that there is no checking if the StateChange is just for an PAR16 50 bulb.

Does anyone have the same issue using other bulbs?
Is it possible that I continue my work and start a pull request when I am done?

Best wishes

Markus

**Comment by markusmazurczak** [comment]
I also filed an issue at eclipse bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=481802
Sorry for that but I am not sure about the correct place :-)

**Comment by kaikreuzer** [comment]
Thanks, @markusmazurczak. The right place is where the source code is located - so in the case of the hue binding, this is Eclipse. I therefore close this issue here.
