### ISSUE TITLE
openhab.target has some location errors

### ISSUE THREAD

**Issue by masoud-omidvar** [openhab/openhab2#463]
hi,

Today I've tried twice getting "OpenHAB 2 Development" via Eclipse installer. Everything goes well, except after getting sources from github, build fails. When I looked at Window->Preferences->Plug-in Development->Target Platform->"openHAB 2 Target Platform" 

![image](https://cloud.githubusercontent.com/assets/8285663/11238905/10bb5872-8dfe-11e5-8ff8-1a25e3640624.png)

And when I opened targetplatform/openhab.target in Target Editor it shows error on:
https://github.com/openhab/openhab.repo/tree/master/jetty-deps

![image](https://cloud.githubusercontent.com/assets/8285663/11238605/0af554bc-8dfc-11e5-9714-01b18679a532.png)

**Comment by kaikreuzer** [comment]
This is a weird message as obviously the repo is available. I suspect that somehow your Eclipse instance failed to download from this repository and does not retry it by itself now.

Could you edit the file openhab.target with a text editor and increase the "sequenceNumber" in the header by one? This should make Eclipse trying to resolve the complete TP again.

**Comment by masoud-omidvar** [comment]
Dear Kai,

Many thanks for your quick reply. I am on the master branch at:

commit 0db2d15eab9a6a2611d02252b526b00f69516e0f
Author: Kai Kreuzer <kai@openhab.org>
Date:   Tue Nov 10 23:56:37 2015 +0100

    added LCN 1.x binding to list
    Signed-off-by: Kai Kreuzer <kai@openhab.org>

**Comment by masoud-omidvar** [comment]
I have incremented from 143 to 144 and nothing changed:

![image](https://cloud.githubusercontent.com/assets/8285663/11239037/d66db204-8dfe-11e5-89b2-33b038b986ef.png)

**Comment by kaikreuzer** [comment]
To me it looks as if a lot has changed. So simply the the same again and see what the result is this time.
Do you have a flaky internet connection or some proxy inbetween?

**Comment by masoud-omidvar** [comment]
> Do you have a flaky internet connection or some proxy in between?

yes. What can i do ?

**Comment by kaikreuzer** [comment]
Either beat up your network admin or keep trying to resolve the TP the way I explained above...

**Comment by masoud-omidvar** [comment]
thanks a lot.
