### ISSUE TITLE
Phillips Hue and state

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab2#466]
Hi,
I really don't know where to find an answer to my question. I am trying to get the state of a lamp, in order knowing if it is ON or OFF. I think having a channel for that would be a good idea, but there is no such thing.

I manage to switch the lamp on or off, by using the two channels, but the state they provide give no answer if it is ON or OFF. I am guessing, this is a work in progress, since when I am in Paper UI and I use the switch, the other channel is not affected directly.

**Comment by kaikreuzer** [comment]
Please use the forum at https://community.openhab.org/ for general question. If you are new to openHAB, better stick to openHAB 1 for the moment as well.
