### ISSUE TITLE
Packaging all features in the distro

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#472]
@maggu2810, in https://github.com/openhab/openhab2/issues/375#issuecomment-148711132 you answered me:
```
For the openhab2-runtime distribution of the karaf branch the bundled repo is located using "runtime/karaf/system/".

Sure, you could drop all remote repos.
```
I just noticed now that the distribution only contains the core OH2 bundles in runtime/karaf/system, but e.g. not a single binding or other addon. So installing a feature currently fails, if the artifact is not found by chance in your local Maven repo (which happened to always be the case for me, hence I never noticed).

So we still need to package them as a kar or through some other way. Could you look into this?

**Comment by maggu2810** [comment]
see #476

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/openhab/openhab2/pull/476 - thanks!
