### ISSUE TITLE
Paper UI not visible anymore since CometVisu merge

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab2#498]
I am running a pretty vanilla OH2, last installed from Jenkins Build 421 (git hash 9feb8420480ad4347fcc47f7ffb98e0e39fd4d7c  )

Running this, and going to http://my-server:myport/, I am redirected to /start/index, where I can see only the tiles for CometVisu, REST API and Classic UIs.

**Comment by kaikreuzer** [comment]
This is related to a bundle name change at ESH, it was only a co-incidence with the CometVisu.
Should be fixed with #500.
