### ISSUE TITLE
rest documentation broken

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#505]
Using the current master, the openHAB 2 Eclipse IDE and the openHAB Runtime launch configuration results in a non working rest documentation (on my machine).

I get the message:
"Can't read from server. It may not have the appropriate access-control-origin settings."

I think this is related to #504

**Comment by kaikreuzer** [comment]
It works for me - could you check if your target platform has been correctly resolved and activated after the update? You will need the com.eclipsesource.jaxrs.provider.swagger and com.eclipsesource.jaxrs.swagger-all bundles in your launch config.

**Comment by maggu2810** [comment]
I opened the launch configuration and see that the swagger-provider and swagger-all is selected (in the target platform).

* using http://127.0.0.1:8080/doc/index.html results in the header and as content "Can't read from server. It may not have the appropriate access-control-origin settings."

* http://localhost:8080/rest/swagger.json gives me json data, so I would assume swagger is running at all.

**Comment by kaikreuzer** [comment]
Ok, so I guess it will work if you use http://localhost:8080/doc/index.html instead.

We could try to find a way to make Swagger always access the server that you have entered in your browser, otherwise it considers it a CORS request.

**Comment by maggu2810** [comment]
That is correct. :+1:
So closing this issue or wait for a solution that does work using the IP address and the hostname?

**Comment by kaikreuzer** [comment]
Probably better waiting as it will pop up again once we deploy it on http://demo.openhab.org:9080/doc/index.html

**Comment by maggu2810** [comment]
> We could try to find a way to make Swagger always access the server that you have entered in your browser

:+1: 
Also using another port (e.g. 8181 or 9080) would mean, that the user have to change the json URL path manually as it is hard coded (host = localhost; port = 8080).

**Comment by dvanherbergen** [comment]
The rest doc also has a css issue. In Safari, some text is invisible. In Chrome it works normal.
![rest-doc-safari](https://cloud.githubusercontent.com/assets/1044349/11692491/fcb192f8-9e9f-11e5-9125-5cac0ada52d4.png)

**Comment by dvanherbergen** [comment]
Both issues are fixed by #540 .

**Comment by kaikreuzer** [comment]
Very cool - thanks a lot, @dvanherbergen (and btw, happy belated birthday ;-))
