### ISSUE TITLE
Paper UI (OH2 style): Control missing

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#506]
Using the openHAB 2 paper ui fragment / theming result in a missing "Control" (http://127.0.0.1:8080/ui/index.html#/control) link.

**Comment by kaikreuzer** [comment]
This is by intention. The Paper UI is not meant to be used as a control UI in openHAB - we have plenty of other UIs for this purpose :-)

**Comment by mikecarr** [comment]
I am confused, Control tab is supposed to be blank?

**Comment by kaikreuzer** [comment]
That was in 2015. Now, there is a Control tab again.
