### ISSUE TITLE
Analyze and improve startup time and resource usage

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#514]
When trying the runtime on a RasPi 2, it took a couple of minutes to start up, while the "old" distribution takes only around 20 seconds on the same hardware.
I assume that there might be still something wrong regarding trying to check external repositories or something. Otherwise I would not know why it could be so much slower.

**Comment by kaikreuzer** [comment]
I just compared the current openHAB demo distribution zip with the Karaf distribution with installed demo (after starting, simply run `feature:install openhab-demo`) using jvisualvm.

The results are worrying:
jvisualvm shows a used heap of 300MB (vs 75MB) and around 150 threads vs. 75 threads.

It seems as if the Karaf distribution is MUCH heavier than our normal distribution.
@maggu2810 If we cannot solve this, this could become a blocker for the whole approach; at least, we would probably have to offer both variants, which isn't desirable at all.

@dvanherbergen, is this maybe something you could analyze? Why is there such a big difference and what are our options to reduce it?

**Comment by dvanherbergen** [comment]
@kaikreuzer I've missed most of the discussion, so what is the ultimate goal? keep 2 runtimes or eventually move towards karaf only? I will look into this as soon as possible, but this weekend some time is reserved for St. Nicholas. Does he visit Germany too?

**Comment by dvanherbergen** [comment]
@kaikreuzer never mind, I just reread your comment and noticed the goal is to move to karaf only. Time to put my glasses on...

**Comment by kaikreuzer** [comment]
>  the goal is to move to karaf only

Correct, that was/is the plan!

> St. Nicholas. Does he visit Germany too?

Yes, but only at night ;-)

**Comment by dvanherbergen** [comment]
wow... I just launched the openhab-runtime in master and the two runtimes in the karaf branch (without installing the openhab-demo). They all have different very usage profiles:
* the equinox runtime: heap allocation starts at 500Mb, heap usage starts around 80Mb and goes up to 190MB or 300Mb before garbage collection kicks in and it drops back to 50Mb.
* the openhab runtime in the karaf branch: heap allocation starts at 990Mb and climbs to 1.2Gb, heap usage starts around 500Mb and climbs to 690Mb before GC kicks in and drops it to 78Mb.
* the openhab-karaf runtime in the karaf branch: heap allocation starts at 500Mb but very quickly expands to 1.5Gb, heap usage starts around 127Mb and climbs to 900Mb before GC kicks in and drops it to 76Mb. 
This will be an interesting one to figure out...

**Comment by kaikreuzer** [comment]
> openhab-karaf runtime

Forget about this one. The "openhab runtime in the karaf branch" is simply a repackaging of the openhab-karaf to adapt the folder structure to openHAB needs.

**Comment by kaikreuzer** [comment]
@maggu2810: I suspect that this is due to https://github.com/openhab/openhab2/pull/476 - it probably now scans all jars that we package at startup for their content, instead of treating them simply as a repository from where it can potentially load the add-ons if required.

@dvanherbergen : It would be interesting to compare the resource requirements of a plain Karaf runtime (http://karaf.apache.org/index/community/download.html), to see what would be the lowest limit of all efforts that we could reach.

**Comment by dvanherbergen** [comment]
When I run with the JVM with option -XX:+UseG1GC , it behaves much better. No unnecessary large heap is allocated and unreferenced objects are released quickly.
The openhab-karaf runtime (without demo) dropped after a forced GC to an allocated heap of 100Mb and usage fluctuating between 33Mb and 86Mb.
The PermGen space seems big though. Do we really need 50Mb worth of classes?

**Comment by dvanherbergen** [comment]
Using the default garbage collector, the plain karaf runtime starts at 75Mb used and drops back to a minimum of 26 after a while and then starts climbing again. PermGen is around 25Mb.
With the G1 collector, heap usage starts around 30Mb and then slowly starts climbing.
When forcing GC, usage goes down to 12Mb.

So overall, with the GC1 collector heap usage seems better managed, so I suggest we use this one as the default. I'll have a look at the number of threads next.

**Comment by dvanherbergen** [comment]
A little after the container starts, I'm seeing a huge spike in live threads. There around 200 threads created for uPnP, which are discarded afterwards, leaving the average live threads around 100. After a while, uPnP spins up yet another bunch of threads (50 to 100), which are again quickly discarded. 
Something doesn't seem right there, but this behaviour is the same for the equinox & karaf versions.
The difference between the base load of 50 live threads on equinox and 100 live threads on karaf, seems to be caused mainly by pax-web (10 threads) and another thread pool (25 threads) which I haven't been able to identify yet. To be continued...

**Comment by kaikreuzer** [comment]
> so I suggest we use GC1 as the default

+1

> There around 200 threads created for uPnP

This is a bug I discovered in jUPnP yesterday as well - it will be fixed in the next days, so don't worry about that for the moment.

> caused mainly by pax-web (10 threads) and another thread pool (25 threads)

Ok, this is the important difference then that needs to be investigated!

**Comment by dvanherbergen** [comment]
20 of the unidentified threads belong to a thread pool dedicated for org.apache.felix.eventadmin.impl.handler.EventAdminImpl.  Apparently, felix' EventAdmin's default is 20 threads for event delivery. This can be changed using by setting the property org.apache.felix.eventadmin.ThreadPoolSize. The property should be set to a property higher than 1 otherwise it will fallback to the default of 20. The max pool size is defined by the property value + 10, so I suggest we set it the default to 3. That should be more than sufficient for openhab.

**Comment by dvanherbergen** [comment]
The pax-web threads are supposedly configurable by the properties org.ops4j.pax.web.server.minThreads=3
org.ops4j.pax.web.server.maxThreads=5
Some of the other extra threads (6) are due to the ssh server which is built in.
I will check tomorrow if reducing the threads using these properties works.

**Comment by maggu2810** [comment]
Thanks for your detailed informations. IMHO the ssh server shoult be disabled for the normal OH runtime. I kept them alive for my daily work. Nothing that is necessary for a release. Perhaps we could add a few such features to the extension service.

**Comment by dvanherbergen** [comment]
It turns out that there is only 1 ssh thread running by default. When you connect to the console using the ./client, it fires up another 5, so I'm not sure if we would be able to get rid of this.
And for me personally, having ssh directly to the console would be convenient too..

**Comment by dvanherbergen** [comment]
I created PR 514 for updating the GC and reducing the eventadmin threads. This brings heap usage down to around 80Mb and the number of live threads to 73.
No success with the jetty related threads yet, as I'm getting errors like 
> java.lang.IllegalStateException: Multiple servlets map to path: /basicui/app/*: org.ops4j.pax.web.service.spi.model.ServletModel-16,org.ops4j.pax.web.service.spi.model.ServletModel-18
	at org.eclipse.jetty.servlet.ServletHandler.updateMappings(ServletHandler.java:1488)

**Comment by dvanherbergen** [comment]
When starting, pax-web shows this annoying warning message:
> [ce.jetty.internal.JettyServerWrapper] - failed to parse and instantiate of javax.servlet.ServletContainerInitializer in classpath

This is caused by an invalid service defined in the jax-rs dependency. I've opened an issue for this: hstaudacher/osgi-jax-rs-connector#131

**Comment by maggu2810** [comment]
> Multiple servlets map to path: /basicui/app/*: 

@dvanherbergen This should be solved by https://github.com/eclipse/smarthome/pull/699

**Comment by maggu2810** [comment]
>> jvisualvm shows a used heap of 300MB (vs 75MB) and around 150 threads vs. 75 threads.

> This brings heap usage down to around 80Mb and the number of live threads to 73.

So, all fine now?

**Comment by dvanherbergen** [comment]
Memory consumption is fine. Even an Xmx of 128Mb seems to work OK.
The total number of threads (live+daemon) is still higher, as Karaf adds some additional management threads. We may be able to optimize this further, but it shouldn't hinder performance too much.
Startup time is still rather slow. During the first startup, all bundles are installed and that takes some time. Subsequent starts are faster, but still take some time. There may be some more room for optimisation, so  I wouldn't close this issue yet.

**Comment by ANierbeck** [comment]
On the jetty/pax-web front if there is anything I can help with, just gimme a ping :-)

**Comment by dvanherbergen** [comment]
Great! As it happens, I do have a question for you :-)
Pax-web launches a number of org.ops4j.pax.web.service.jetty.internal.LateInvalidatingHashSessionManager threads. 
Is there a way to limit the number of threads being spawned? Would a single thread not be sufficient to scavenge sessions for multiple jetty threads?

**Comment by ANierbeck** [comment]
Actually those are handled by Jetty itself, Pax-Web only provides an alternative SessionManager, which is needed for the HttpService. So in that case I'd think, if we reduce the Jetty-Threads it'll be in sync.

**Comment by dvanherbergen** [comment]
That doesn’t seem to work. When using org.ops4j.pax.web.server.maxThreads = 7, the number of ‘base’ jetty threads is 7. And then there is an additional 8 threads for the SessionManager.
Now, when I set the min and max both to 20, the number of base threads is 20 and there are still 8 threads for the SessionManager. So it would appear that the number is fixed.

**Comment by ANierbeck** [comment]
Actually the SessionManager is bound to every HttpContext, so if you have 8 bundles using a session manager you have all of them running.

**Comment by kaikreuzer** [comment]
Does this mean we should make sure to use a single instance of HttpContext?
I wasn't aware that we are creating so many instances. But indeed, we usually use `httpService.createDefaultHttpContext()`, which creates a new instance every time.
Shall we introduce a special HttpContextService in ESH? Does anyone know how well this can be integrated with Jersey and possible authentication/session mechanisms?

**Comment by ANierbeck** [comment]
Hi,

no this doesn't necessarily mean that. Usually you have one Bundle with one
HttpContext.
And it's fine to use the httpService.createDefaultHttpContext for it.
Now depending on your use-case with Pax-Web it's possible to share the
Context between Bundles.
For example if you want to separate filters from servlets.
In this last case you can use pax-web WebContainer Interface to create
SharedContextes.
As I'm not sure how those use-cases are handled right now, I'd say it's
something that needs to be investigated,
to find out what suits best.

2015-12-13 11:40 GMT+01:00 Kai Kreuzer <notifications@github.com>:

> Does this mean we should make sure to use a single instance of HttpContext?
> I wasn't aware that we are creating so many instances. But indeed, we
> usually use httpService.createDefaultHttpContext(), which creates a new
> instance every time.
> Shall we introduce a special HttpContextService in ESH? Does anyone know
> how well this can be integrated with Jersey and possible
> authentication/session mechanisms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab2/issues/514#issuecomment-164246561>.
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by dvanherbergen** [comment]
I had another look at the startup time. By commenting out the CoreActivator.startRuleEngine() method, I was able to reduce my startup time by 12 seconds ;-)

The hardcoded waits in there should be replaced with a different solution. I suggest a change the FolderObserver in ESH. It could send out a ModelsLoadedEvent after it has done the initial load of the all available models. Then the rule engines can wait for this event to occur before they start processing rules.

**Comment by kaikreuzer** [comment]
Interesting :-)
This code is indeed a dirty hack and I am ashamed of it ;-)
Nonetheless I remember that I didn't find any other solution to the problem at the time - startup rules should only be executed when the system has started up.
A change that I did at the same time as introducing this hack is this: https://github.com/openhab/openhab2/commit/e610bce83d8718136e07506e9707473ae9788aef#diff-9eb4f271b48006052139077eded10b83R84
The core bundle is started as the very last one, so it actually should never block 12 seconds, because the other services should be there already. I guess this setting has been lost in the Karaf distro. Maybe you can gain already 10 seconds by changing the start level of the bundle as well?

**Comment by dvanherbergen** [comment]
The start level change has indeed been lost. The core bundle in the karaf branch starts at level 80, which is the default.

**Comment by maggu2810** [comment]
It was a long way to get rid of the start level requirements and I was happy that it works at least.
As I have not done start up time analyzes, I was fine with the current state.
If never seen this hack before, IIRC I do not use that core bundle at all.
Would be great if the situation could be solved without start level changes in a non hackish way. :wink:

**Comment by kaikreuzer** [comment]
> Would be great if the situation could be solved without start level changes in a non hackish way. :wink:

I fully agree and you are both invited to come up with a clean solution. I actually remember that I looked at something like a OSGi start level service, but I didn't succeed in being notified when a certain start level is reached (and then trigger the startup rule execution). If any of you finds a way how to do this, that would be great :-) Until then I would prefer to have the start level changed for this bundle.

**Comment by dvanherbergen** [comment]
One option would be to poll the start level in a separate thread until it reaches 100 and then publish a SystemStartedEvent. 
Polling the start level can be done using https://osgi.org/javadoc/r4v43/core/org/osgi/framework/startlevel/FrameworkStartLevel.html#getStartLevel().
The rule engine could then listen for the SystemStartedEvent to trigger startup rules.

**Comment by kaikreuzer** [comment]
Where should this polling thread be best located? Would we invent a new bundle for it?

**Comment by kgoderis** [comment]
Sorry for being late to the party, but you guys have an interesting chat ;-) . Reading through all the optimisations you are doing, I was wondering if this is the time to look as well to the startup order of things in ESH? Cfr various of my posts on the different fora, as very very early adaptor of ESH OH2, there is a need to synchronise a bit how things are loaded and parsed wrt Items, Things, and Rules. Still as of today, with an ESH core not older than two weeks, I have very random behaviour at startup where .items are not parsed at all, updates are received for non-existing Items and so forth.

**Comment by kaikreuzer** [comment]
@kgoderis You are well aware that @maggu2810 just mentioned in https://github.com/openhab/openhab2/issues/514#issuecomment-165447988 that he is actually more rigid than I am when it comes to abolishing start level order of bundles. So no, it might not the best time to come up with that ;-)

**Comment by dvanherbergen** [comment]
> Where should this polling thread be best located? Would we invent a new bundle for it?

How about org.eclipse.smarthome.core ?

**Comment by dvanherbergen** [comment]
@kgoderis to really eliminate funky stuff startup issues, I believe you would also need to block event publishing during startup. This could be a possible solution:
1. Both the rule engine and event publisher startup in an inactive mode
2. In the core bundle, the system startup level is polled until the system is fully started and then emits a SystemStartEvent.
3. The event publisher picks up the event and starts passing through events. In turn it also emits an BusStartedEvent
4. The rule engine picks up the BusStartedEvent and kicks off the startup rules.
With this approach, the start level of bundles is irrelevant.

**Comment by maggu2810** [comment]
@dvanherbergen I like your idea.

But I think you can't use https://osgi.org/javadoc/r4v43/core/org/osgi/framework/startlevel/FrameworkStartLevel.html#getStartLevel().
For which start level you would like to check?
The start level that are used for bundles is product specific. The Eclipse IDE for openHBA currently uses start level 1-5. You cannot rely that at start level e.g. 100 the Eclipse SmartHome framework is loaded correctly if I use start level 110 for all ESH bundles.

**Comment by kaikreuzer** [comment]
Well, the start level for "system up" would have to be configurable through config admin, I guess.

**Comment by dvanherbergen** [comment]
If you use the command system:start-level on the karaf console, you can see it the 'final' level where the runtime stops incrementing is 100. I'm not sure if this is the same for both equinox and felix.

**Comment by dvanherbergen** [comment]
When using the equinox runtime with -Dosgi.startLevel=100, it also increments start levels up to 100, so that should work.

**Comment by maggu2810** [comment]
If it is configurable I am fine with waiting for a special start level and act if this is reached.
For Karaf you could set the startup level that should be reached after start using etc/config.properties "org.osgi.framework.startlevel.beginning=100".

**Comment by maggu2810** [comment]
What about this one:
http://eclipsesource.com/blogs/2013/01/23/how-to-track-lifecycle-changes-of-osgi-bundles/

**Comment by dvanherbergen** [comment]
It says: 
> A BundleListener can only receive notifications after it has been started.

wouldn't that require us to changing startup level sequences again?

**Comment by maggu2810** [comment]
Just one other idea.
If we want to wait until the bundle1, bundle2 and bundle3 has been started.
Would it be an option that every bundleX register (after successful start) a service bundleXready or something similar and stop that dummy service if it is stopped.
Another bundle is using a service tracker to track that services and if all are ready it signals an system completely started (through event or another service)?

**Comment by ANierbeck** [comment]
Guys, afaik Karaf has a service which is available in case a certain
StartLevel is reached. This one is also used to wait for Karaf BootFinished
in the Pax-Exam tests.
Btw. the Interface is called BootFinished, maybe that'll help you already
and get rid of the StartLevel thinking ;)

2015-12-17 15:37 GMT+01:00 dvanherbergen <notifications@github.com>:

> It says:
>
> A BundleListener can only receive notifications after it has been started.
>
> wouldn't that require us to changing startup level sequences again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab2/issues/514#issuecomment-165468125>.
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by dvanherbergen** [comment]
@kaikreuzer will smarthome also move to karaf? If so, then BootFinished sounds like a good option.

**Comment by ANierbeck** [comment]
Just in Case one wonders,
if all BootFeatures are installed and the feature service tells that it's
done,
the BootFinished Service is published [1]

regards, Achim

[1] -
https://github.com/apache/karaf/blob/master/features/core/src/main/java/org/apache/karaf/features/internal/service/BootFeaturesInstaller.java#L115

2015-12-17 15:49 GMT+01:00 dvanherbergen <notifications@github.com>:

> @kaikreuzer <https://github.com/kaikreuzer> will smarthome also move to
> karaf? If so, then BootFinished sounds like a good option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab2/issues/514#issuecomment-165471629>.
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by maggu2810** [comment]
@ANierbeck Hi, you know, I love Karaf :wink:, but I don't believe it is an option for the Eclipse SmartHome framework. The framework does not depend on stuff like Karaf etc.

For openHAB it would be an option but not for Eclipse SmartHome bundles.

**Comment by maggu2810** [comment]
So I think we have to use something in the Eclipse SmartHome framework that does not depend on Karaf and does (hopefully) not depend on start levels.

**Comment by dvanherbergen** [comment]
> Would it be an option that every bundleX register (after successful start) a service bundleXready or something similar and stop that dummy service if it is stopped.
Another bundle is using a service tracker to track that services and if all are ready it signals an system completely started (through event or another service)?

That would require knowing up front how many bundles will be loaded...

**Comment by kgoderis** [comment]
> @kgoderis You are well aware that @maggu2810 just mentioned in #514 (comment) that he is actually more rigid than I am when it comes to abolishing start level order of bundles. So no, it might not the best time to come up with that ;-)

Maybe we need even more/better start levels to make the startup more deterministic? behold I am not a Karaf expert at all, I am just suggesting the opportunity ;-)

**Comment by kgoderis** [comment]
> @kgoderis to really eliminate funky stuff startup issues, I believe you would also need to block event publishing during startup. This could be a possible solution:
> 1. Both the rule engine and event publisher startup in an inactive mode
> 2. In the core bundle, the system startup level is polled until the system is fully started and then emits a SystemStartEvent.
> 3. The event publisher picks up the event and starts passing through events. In turn it also emits an BusStartedEvent
> 4. The rule engine picks up the BusStartedEvent and kicks off the startup rules.
> With this approach, the start level of bundles is irrelevant.

+1

This could be generalised for every core element. e.g. Item parsing and so forth. Also, we should make sure that any thread that deals with parsing or alike is not exiting ungracefully (I think it is still the case, making debugging troublesome for one)

**Comment by maggu2810** [comment]
Have another idea. Will check it tomorrow, have to drink beer now ;)

**Comment by dvanherbergen** [comment]
> This could be generalised for every core element. e.g. Item parsing and so forth. 

Not only that, but if we think long term, I believe this approach could also work in a distributed setup. So that your rule would not start until the master and all slave instances have started.

@maggu2810 enjoy!

**Comment by ANierbeck** [comment]
@maggu2810 ... I didn't suggest it :-)
I wasn't even aware of that project.

All others, never the less one should really get rid of thinking
start-levels is a good idea to manage your application, rather make sure
you depend on certain services instead.

regards, Achim


2015-12-17 16:33 GMT+01:00 dvanherbergen <notifications@github.com>:

> This could be generalised for every core element. e.g. Item parsing and so
> forth.
>
> Not only that, but if we think long term, I believe this approach could
> also work in a distributed setup. So that your rule would not start until
> the master and all slave instances have started.
>
> @maggu2810 <https://github.com/maggu2810> enjoy!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab2/issues/514#issuecomment-165484987>.
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by kaikreuzer** [comment]
> @kaikreuzer will smarthome also move to karaf? 

Eclipse SmartHome will stay a set of OSGi bundles to be picked up. So no, Karaf etc. won't be introduced there.

But what we should do is to design these bundles in a way that solutions like openHAB can define how they want to handle the system lifecycle. As @ANierbeck suggests, in ESH, all we want to make sure is that these bundles are good OSGi citizens and respect the dynamic features of OSGi - thus they should clearly declare their dependencies through services and should cope with any situation where services come and go.

For our concrete problem at hand, we are actually only talking about the right moment to launch the startup rules, right? So in ESH, we could simply remove the logic that says when is "startup" (at the moment when that rule engine bundle is started, which is anyhow a bad idea) and let that be triggered from external, e.g. a bundle that depends on the RuleEngine and calls runStartupRules() on it.
For openHAB 2, we could easily implement this using the BootFinished service, don't you think?

Btw, I didn't have a beer tonight, so maybe @maggu2810's idea is better after all ;-)

**Comment by maggu2810** [comment]
@kaikreuzer 
Could we move the start / stop code of the bundle activators of the org.eclipse.smarthome.model.*.runtime classes to DS implementations (immediate=true)?
So openHAB could create another DS (e.g. BootupDone) that reference the services it needs for startup (cardinality=1..1, policy=static) and trigger runStartupRules in that activate method?

**Comment by maggu2810** [comment]
> So in ESH, we could simply remove the logic that says when is "startup"

As a collection of bundle that are no product themselves we should remove that.

**Comment by kaikreuzer** [comment]
> Could we move the start / stop code of the bundle activators of the org.eclipse.smarthome.model.*.runtime classes to DS implementations (immediate=true)?

Possibly yes, but I can imagine that we run into all kinds of Xtext initialization problems - getting Xtext with its dependencies to start up correctly has always been a challenge... But we can of course have a try.

**Comment by maggu2810** [comment]
Changes are prepared, will test it later (other stuff to do)...
https://github.com/eclipse/smarthome/compare/master...maggu2810:ds-model-runtime?expand=1

**Comment by kgoderis** [comment]
I am a complete noob when it comes to Karaf (side note: maybe I am not alone but I do not fully grasp what you try to do with Karaf in the first place), but based on what I understand, could a solution not lie in a clever usage of "system" Events on the ESH bus? At least some bindings - if they need to - or other building blocks from the core can figure out when to do stuff, e.g. use RuleEngineStartedEvent, ItemsLoadedEvent  and so forth... Something that is maybe not tied to the deep inner workings of the OSGi / Karaf .... And maybe it will make the startup of the whole runtime more deterministic, because, if not, we will end up with a lot of frustrating folks not understanding why their stuff is not working anymore when they go from OH1 to OH2

**Comment by dvanherbergen** [comment]
> So openHAB could create another DS (e.g. BootupDone) that reference the services it needs for startup (cardinality=1..1, policy=static) and trigger runStartupRules in that activate method?

Why create another DS if you can use the karaf built-in BootFinished service? I believe it would be better to use BootFinished instead. This way, you know all bundles will have been loaded. If you create BootupDone, how will you know that all the bindings which are needed to execute the result of the startup rules will be loaded? 


> based on what I understand, could a solution not lie in a clever usage of "system" Events on the ESH bus?

These are not mutually exclusive. It would be possible to use the BootFinished service to then trigger a SystemStartedEvent.

**Comment by kaikreuzer** [comment]
> Why create another DS if you can use the karaf built-in BootFinished service?

I guess the idea is to have the BootFinished service to depend on BootFinished, RuleEngine, etc. - so it will be activated as soon as all these services are in place.

**Comment by dvanherbergen** [comment]
Ah, OK. So BootupDone would depend upon BootFinished, so that it activates upon receiving that service. And then it could send the SystemStartedEvent ;-)

**Comment by maggu2810** [comment]
I have create a PR for Eclipse SmartHome, so we could test if this goes in the right direction. https://github.com/eclipse/smarthome/pull/757

**Comment by kaikreuzer** [comment]
And for the time being I have created https://github.com/openhab/openhab2/pull/565 as a quick fix :-)

**Comment by kaikreuzer** [comment]
Closing this as I started follow-up discussion in https://github.com/openhab/openhab-distro/issues/10
