### ISSUE TITLE
Remove tar.gz distribution?

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab2#515]
So far we always only had a single download zip file and never the choice between zip and tar.gz.
Since we manage to package the start scripts within the zip with the correct execution flags for Linux, I wonder if we should stay with just the zip file and remove the tar.gz again. In all these years, nobody really asked for that. What do you think?

**Comment by maggu2810** [comment]
If the file attributes are preserved it doesn't matter.I never used the zip files. As a linux guy I am using tar.gz :wink:

**Comment by hakan42** [comment]
I have to set the executable bits on shell scripts after unpacking the zip I fetch from jenkins nighty builds. Some thing with my unzip binary perhaps (running on Raspbian latest)

**Comment by kaikreuzer** [comment]
@hakan42 Are you referring to the Karaf distribution zip?

**Comment by hakan42** [comment]
Oops, sorry to muddle the waters, I did not notice the karaf label in the github email... I am using the old-fashioned build

**Comment by dvanherbergen** [comment]
+1 on removing the tar.gz. 
However, both zip and tar.gz are being always generated by the karaf-maven-plugin, this is not configurable and only the generated tar.gz contains the correct file permissions. 
So except from submitting a patch to the plugin, we could generate both, delete the generated zip and then repackage the tar.gz one into a zip.

**Comment by maggu2810** [comment]
IMHO if read about a config param to skip the generation of archive types. But perhaps it has been another plugin. Let's look at the sources.

**Comment by kaikreuzer** [comment]
I would not mind if the karaf distro still creates the tar.gz during the build as long as we only create the zip for the openhab distribution (i.e. we can simply adapt the assemble plugin config)

**Comment by dvanherbergen** [comment]
@maggu2810 you are right. I had a quick look at the sources and it contains undocumented parameters to disable zip and/or tar.gz generation. It will also set the executable bits on .bat files for zip and on non-bat files for tar.gz.

What if we would just disable the karaf maven plugin archive generation altogether and do only a single maven assembly directly to the zip archive in openHAB format? That would give us the good zip and get rid of the repackaging step. I'm happy to give this a try...

**Comment by maggu2810** [comment]
Give it a try. We could try to use the maven-assembly-plugin to package ${project.build.directory}/assembly directly.
If we could build only one archivs at all, it is fine.
But if we generate a zip only, we have to ensure, that he file modifiers are not lost.

**Comment by kaikreuzer** [comment]
> But if we generate a zip only, we have to ensure, that the file modifiers are not lost.

I think this is already ensured as they are manually set:
https://github.com/openhab/openhab2/blob/karaf/distributions/openhab-runtime/src/main/descriptors/bin.xml#L77
I have only noticed that this setting does not seem to always work - the build from cloudbees are sometimes lacking the flags, while local builds on my Mac always work as expected. But this is how it works on openHAB 1 and as I said, I do not remember any complaints about it...

**Comment by dvanherbergen** [comment]
Implemented in PR #536
