### ISSUE TITLE
Extension service (karaf)

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#531]
Either I don't understand the feature extension service or there is a bug.

using <code>feature:list | grep -i openhab-ui</code> I get the following list

```text
openhab-ui-basic                      | 2.0.0.SNAPSHOT         |          | Uninstalled | org.openhab.feature.aggregate.xml  | Basic UI
openhab-ui-classic                    | 2.0.0.SNAPSHOT         |          | Uninstalled | org.openhab.feature.aggregate.xml  | Classic UI
openhab-ui-cometvisu                  | 2.0.0.SNAPSHOT         |          | Uninstalled | org.openhab.feature.aggregate.xml  | CometVisu
openhab-ui-dashboard                  | 2.0.0.SNAPSHOT         |          | Started     | org.openhab.feature.aggregate.xml  | Dashboard
openhab-ui-paper                      | 2.0.0.SNAPSHOT         | x        | Started     | org.openhab.feature.aggregate.xml  | Paper UI
```

The Extension type "user interface" in the Paper UI shows me

```text
Basic UI 
ui-basic - 2.0.0.SNAPSHOT

Paper UI
ui-paper - 2.0.0.SNAPSHOT

CometVisu
ui-cometvisu - 2.0.0.SNAPSHOT
```

**Comment by kaikreuzer** [comment]
You mean the Classic UI is missing there? Sounds like a bug, would have to investigate...

**Comment by maggu2810** [comment]
Yes, I missed the Classic UI. If I understand the logic correctly the dashboard should be shown, too (regardless if it is not intended to remove them)...
Should we add the Paper UI to the openhab-runtime feature, so we get this configuration UI after start?

**Comment by kaikreuzer** [comment]
I intended to have the openhab-runtime feature as the "minimal" feature, not even bringing the REST API with it. Maybe we should think about some kind of "standard" feature with a similar set as the demo feature (PaperUI+BasicUI), but without the demo files...

**Comment by maggu2810** [comment]
* minimal runtime = openhab-runtime-base; https://github.com/openhab/openhab2/blob/cef44aa0829e503a446fcdabf48a733569278ddf/features/org.openhab.feature.runtime/src/main/feature/feature.xml#L12

* the runtime of the "normal" distribution = openhab-runtime; https://github.com/openhab/openhab2/blob/cef44aa0829e503a446fcdabf48a733569278ddf/features/org.openhab.feature.runtime/src/main/feature/feature.xml#L4

**Comment by maggu2810** [comment]
But that could be changed...

**Comment by kaikreuzer** [comment]
ok, I am fine with that naming as well. So yes, let's add Paper UI and Basic UI to the runtime then!

**Comment by maggu2810** [comment]
Should be related to https://github.com/eclipse/smarthome/pull/729

**Comment by kaikreuzer** [comment]
fixed with the latest distro
