### ISSUE TITLE
add paper and basic ui to openhab runtime (karaf)

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab2#532]
See: https://github.com/openhab/openhab2/issues/531#issuecomment-163014796

**Comment by maggu2810** [comment]
@kaikreuzer You could add the "karaf" tag and assign this issue to me.

**Comment by kaikreuzer** [comment]
@maggu2810, you should now also have the rights to do that yourself :-)

**Comment by maggu2810** [comment]
Thank you for your trust.

**Comment by kaikreuzer** [comment]
Thank you for your amazing work :+1:
