### ISSUE TITLE
Hue and Nest Binding Issues

### ISSUE THREAD

**Issue by yandreev3** [openhab/openhab2#547]
Hey everyone. Ive slowly been moving up from Wink to Samsung SmartThings, and now I'm trying to get OpenHab to work and it's kicking my a**. I'm attempting to get at least one or two devices to work but all I can get so far are the web UIs (all working except cometvisu).

The two devices I attempted to get working are my nest thermostats and my hue hub with no success in either. The nest plugin does not load and when I type "ss nest" it tells me it is INSTALLED and gives me its ID   and when I type "start [ID NUMBER]"  i get "Unresolved requirement: Require-Bundle: org.openhab.io.rest.lib"   I went ahead and copied the rest lib from openhab into the bundle folder and I keep getting the same error.

The second device I tried is my hue hub. I installed the addon and configured the IP address of my hub. I left the keyphrase to default and changed the refresh time to 5000. Then I went on the Paper UI and added a bind to the hue hub and entered in the IP, Serial number, and my username. I got a message saying that It was not able to authenticate and the console keeps repeating  "2015-12-13 06:34:00.117 [INFO ] [b.hue.handler.HueBridgeHandler] - Hue bridge 192.168.166.186 is not authenticated - please press the pairing button on the bridge.
2015-12-13 06:34:00.119 [INFO ] [ome.event.ThingStatusInfoEvent] - 'hue:bridge:1b6657ad' updated: OFFLINE (CONFIGURATION_ERROR): Not authenticated - press pairing button on the bridge or change username."

I went and pressed the button and nothing happened.

I'm sorry if i am posting this in the incorrect spot but i hope someone can help. Thanks!

**Comment by kaikreuzer** [comment]
Hi @yandreev3, welcome at openHAB!
As you are a new user, I would very much recommend you to look at openHAB 1 (https://github.com/openhab/openhab/wiki)  at the moment (this here is the bug tracker for openHAB 2).

Specifically, the Nest binding is not yet even listed as compatible with openHAB 2 (see https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md).

So the best place to ask for help is our community at https://community.openhab.org/.

Best regards,
Kai
