### ISSUE TITLE
Persistence cron config error failes parser

### ISSUE THREAD

**Issue by jarlebh** [openhab/openhab2#550]
The following persistance file causes the parser of opemnhab2 to stop, I could not figure it out without removing all config files and adding them 1 by 1.
The error is in the cron statement, missing *
```
// Persistence strategies have a name and a definition and are referred to in the "Items" section^M
Strategies {
        everyHour       : "0 0 * * * ?"
        everyDay        : "0 0 0 * * ?"
        everyFive       : "0 0/5 * * ?"
        

        // If no strategy is specified for an item entry below, the default list will be used.
        default = everyDay 
}

/*
 * Each line in this section defines for which item(s) which strategy(ies) should be applied.
 * You can list single items, use "*" for all items or "groupitem*" for all members of a group
 * item (excl. the group item itself).
 */
Items {
        Humidity* : strategy = everyChange, everyHour, restoreOnStartup
        Weather_Temperature : strategy = everyChange, everyHour, restoreOnStartup
        OutTemp : strategy = everyChange, everyHour, restoreOnStartup
        GF_Dining_Light_ZWave : strategy = everyChange
        Out_Sun_Down : strategy = everyChange
        Elevation : strategy = everyFive
}
```

**Comment by kaikreuzer** [comment]
Does the same file work on openHAB 1?

**Comment by jarlebh** [comment]
I guess not(I do not run openhab2 anymore), but the issue is the missing
warning/error message. I could not find any and it just stops parsing of
all other config files also.

man. 14. des. 2015, 18:57 skrev Kai Kreuzer <notifications@github.com>:

**Comment by kaikreuzer** [comment]
I just downloaded the OH2 demo package (https://openhab.ci.cloudbees.com/job/openHAB2/lastSuccessfulBuild/artifact/distribution/target/distribution-2.0.0-SNAPSHOT-demo.zip), created two files demo1.persist and demo2.persist both with the content you have posted.
Starting the runtime, I get
```
2015-12-15 17:40:56.402 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo1.persist'
2015-12-15 17:40:56.422 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo2.persist'
2015-12-15 17:40:56.428 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.rules'
2015-12-15 17:40:56.684 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.script'
2015-12-15 17:40:56.755 [INFO ] [.e.s.m.c.i.ModelRepositoryImpl] - Loading model 'demo.items'
```
so it all loads fine without problems.
I'd suggest to first discuss at https://community.openhab.org/ and if we have identified a reproducible bug, enter an issue at https://github.com/eclipse/smarthome.

**Comment by jarlebh** [comment]
Ok, that's fine. However I quite certain this file made openhab2 fail. The
reason for creating the ticket was the amount of time I used to identify
the mistake. After fixing the cron syntax my system runs normally again.

tir. 15. des. 2015, 17:44 skrev Kai Kreuzer <notifications@github.com>:

**Comment by kaikreuzer** [comment]
As mentioned, with the information that you have provided, I cannot reproduce the problem.
If you have a file where openhab2 fails and stops any further parsing, please be so kind to post it here (best together with an excerpt from the log file).
