### ISSUE TITLE
IDE Setup

### ISSUE THREAD

**Issue by amirehsanijam** [openhab/openhab2#556]
Hi,
I'm want to use openhab2 and I read instructions and see your youtube video about IDE setup. I did exactly what you said but when last step comes it can not download some repositories related to openhab2 platform like GRECLIPSE4.4, LUNA and etc.
When finish perform setup tasks, I face with lots of errors.
I read last issues causes this problem like doing a perform setup task again and again can not download the same target platform repos.
PLZ help me if there is another way.
I'm using KALI 2.0 UNIX OS , Java 1.7, Maven 3.3.9 and Eclipse Mars.1 .

**Comment by kaikreuzer** [comment]
If you had done the initial checkout on Sunday, there might have been some hick-up.
I have just tried the setup now and it works smoothly.

If you continue to have problems, please provide a detailed error with logs and screenshots. It is otherwise not possible to tell what is wrong.

**Comment by amirehsanijam** [comment]
![screenshot from 2015-12-16 16 22 43](https://cloud.githubusercontent.com/assets/7033713/11841324/cc3eeaae-a411-11e5-88b0-bed31eca7c85.png)
![screenshot from 2015-12-16 16 23 54](https://cloud.githubusercontent.com/assets/7033713/11841327/cf0a26fe-a411-11e5-937c-446a39bffe03.png)
thank you for your helping, i do the setup process and clone it again.
Those screenshots are the result i'm totaly confused!

**Comment by amirehsanijam** [comment]
Pleas help me

**Comment by kaikreuzer** [comment]
> but when last step comes it can not download some repositories related to openhab2 platform

This is what screenshots and log files would be needed for - if the setup has failed, it is clear that the workspace shows errors, so you will have to find out what fails before that.

Also try to execute the Help->Perform Setup Tasks again and say if this runs through or shows errors.

**Comment by amirehsanijam** [comment]
![screenshot from 2015-12-16 17 01 46](https://cloud.githubusercontent.com/assets/7033713/11842114/c6c185e6-a416-11e5-8397-7e014022996b.png)
I am diong the Perform Setup Tasks again and errors remain.

**Comment by kaikreuzer** [comment]
So why do you say "it can not download some repositories"?

**Comment by amirehsanijam** [comment]
I'm so sorry Yes, it can not download some repos.
what should i do now? do it again untill it downloaded?
Is there other way to do this?

**Comment by kaikreuzer** [comment]
> Yes, it can not download some repos.

Can you prove this? You screenshot only shows that it currently is downloading it...

**Comment by amirehsanijam** [comment]
Yes, Wait a minute plz.

**Comment by amirehsanijam** [comment]
My internet speed is a little bit slow.
That would be nice you if wait a few moments.

**Comment by amirehsanijam** [comment]
![screenshot from 2015-12-16 17 31 23](https://cloud.githubusercontent.com/assets/7033713/11842754/e5124658-a41a-11e5-88fe-678311920e5d.png)

**Comment by amirehsanijam** [comment]
![screenshot from 2015-12-16 17 32 35](https://cloud.githubusercontent.com/assets/7033713/11842779/0cb47334-a41b-11e5-9169-228ffe3eb7b9.png)

**Comment by amirehsanijam** [comment]
![screenshot from 2015-12-16 17 13 59](https://cloud.githubusercontent.com/assets/7033713/11842804/4db2e460-a41b-11e5-8e0f-02a265febdc4.png)

**Comment by amirehsanijam** [comment]
This photos shows my problem.
The target platform trying to download them but it fails and also the last photo shows repos that  could'nt load to my workspace.

**Comment by kaikreuzer** [comment]
Your internet connections seems to be the problem. "Communication failed" etc. clearly hint at that.
I do not have any recipes on how to resolve a target platform on a flaky internet connection, sorry. Either complain at your admin or try to reload the TP until it is successful.

**Comment by amirehsanijam** [comment]
Thank you so much for your helping.

**Comment by amirehsanijam** [comment]
Is it all right if you put them some where i can access them and manauly add them?
