### ISSUE TITLE
Basic UI: selections cannot be done multiple times

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab2#578]
I have quite a few scenes with commands in the resulting drop down list like "close all rollershutters" and "open all rollershutters". 

In basicui (as well as in greent if I remember correctly) I cannot select the same dropdown item successively. The second selection just has no effect. In the classicui as well as in the iOS-app, the same selection can be done multiple times and the effect is just executed.

Workaround is to select some other item in the list first and then select the former one again. However, this is often not what I want as the other item might trigger unwanted actions. Would have to create empty dummy entries that do nothing.

**Comment by kaikreuzer** [comment]
Thanks for testing the Basic UI, it is very important to get it working smoothly soon. Since the code is maintained at Eclipse, may I ask you to enter all issues about it at https://github.com/eclipse/smarthome/issues? Thanks :-)

**Comment by SuperOok** [comment]
Ok: https://github.com/eclipse/smarthome/issues/784

**Comment by kaikreuzer** [comment]
:+1:
