### ISSUE TITLE
openHAB2-Karaf fails due to wrong Java version

### ISSUE THREAD

**Issue by dvanherbergen** [openhab/openhab2#587]
The karaf branch was updated to use Java 1.8.
The cloudbees build fails because it still uses 1.7:
```
[openHAB2-Karaf] $ /opt/jdk/jdk1.7.latest/bin/java -XX:MaxPermSize=512m -Xmx1024m -cp /scratch/jenkins/maven31-agent.jar:/opt/maven/apache-maven-3.1.1/boot/plexus-classworlds-2.5.1.jar:/opt/maven/apache-maven-3.1.1/conf/logging jenkins.maven3.agent.Maven31Main /opt/maven/apache-maven-3.1.1 /scratch/jenkins/slave.jar /scratch/jenkins/maven31-interceptor.jar /scratch/jenkins/maven3-interceptor-commons.jar 42465
```

**Comment by kaikreuzer** [comment]
Unfortunately, Cloudbees does not offer OracleJDK 8 at all :-(
So I have changed the build to use OpenJDK 8 instead:
```
/opt/jdk/openjdk8.latest/bin/java
```
As there is currently a problem with the cloudbees maven repo, the build fails and I cannot test.

Please note that the build job has also been renamed to https://openhab.ci.cloudbees.com/job/openHAB-Distribution/

**Comment by dvanherbergen** [comment]
Oracle JDK is listed as supported [here] (https://cloudbees.zendesk.com/hc/en-us/articles/203601234-CloudBees-Jenkins-Platform-Supported-Java-Versions).

**Comment by dvanherbergen** [comment]
Maybe it's related to [this] (https://cloudbees.zendesk.com/hc/en-us/articles/204960114-How-to-set-the-available-JDK-versions)

**Comment by kaikreuzer** [comment]
Thanks, that helped! I had to manually add the Oracle JDK to the Jenkins instance and then I was able to select it in the build plan.
