### ISSUE TITLE
KNX connection through NAT

### ISSUE THREAD

**Issue by dafal** [openhab/openhab2#588]
Hi,

I have just migrated my openhab server at home from a centos server to a docker container.  Everything just works fine except the KNX binding.  I found the reason for this.  I see in the code (KNXConnection.java) that the KNXNetworLink method return a KNXNetworkLinkIP with by default the useNat param set to false (line 263).  However, when you use openhab in a docker you have to use NAT (managed by docker itself).

I was able to trace the packet on the router and indeed the Siemens N148 IP interface return the packets to the internal docker ip address.

23:27:54.113919 IP HOST_RUNNING_DOCKER.44292 > SIEMENTS_N148_IP_INT.3671: UDP, length 26
23:27:54.114251 IP SIEMENTS_N148_IP_INT.3671 > INTERNAL_DOCKER_IP.44292: UDP, length 20

Would it be possible to add a setting to be able to set the useNat setting to true in the openhab configuration file ?

In the meanwhile I go through a eibd to bypass the issue.  I am not a java developer but I assume it would not be too complicated to rebuild it with the param set to true.

**Comment by kaikreuzer** [comment]
Not that there is no KNX binding in this repo (openHAB 2 addons).
If you want to discuss a feature request, please do so at https://community.openhab.org/.
For filing bugs on the KNX binding, enter an issue at https://github.com/openhab/openhab/issues.
Thanks!

**Comment by dafal** [comment]
Indeed, my mistake I was in the wrong repository.  Sorry.
