### ISSUE TITLE
New OpenHab 2 Setup (openHAB 2 Feature Verification Failure)

### ISSUE THREAD

**Issue by mickey4u** [openhab/openhab2#590]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] openHAB Feature Addons External .................... SUCCESS [  2.076 s]
[INFO] openHAB 2 Feature Addons ........................... SUCCESS [ 13.200 s]
[INFO] openHAB 2 Feature Verification ..................... FAILURE [ 48.294 s]
[INFO] openHAB Products ................................... SKIPPED
[INFO] openHAB Runtime Application ........................ SKIPPED
[INFO] openHAB P2 Repository .............................. SKIPPED
[INFO] openHAB Target Platform ............................ SKIPPED
[INFO] openHAB Distribution ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:57 min
[INFO] Finished at: 2016-01-01T04:44:48-05:00
[INFO] Final Memory: 102M/1992M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openhab-addons-verify: Could not resolve dependencies for project org.openhab.addons:openhab-addons-verify:pom:2.0.0-SNAPSHOT: Could not find artifact org.openhab.addons:openhab-addons:xml:features:2.0.0-SNAPSHOT in jcenter (https://jcenter.bintray.com/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openhab-addons-verify

**Comment by kaikreuzer** [comment]
Should already be fixed by https://github.com/openhab/openhab2/pull/589
