### ISSUE TITLE
Validation (org.eclipse.jetty.annotations)

### ISSUE THREAD

**Issue by mickey4u** [openhab/openhab2#591]
When I try running a binding, a dialog appears like this
![screenshot from 2016-01-01 05-12-36](https://cloud.githubusercontent.com/assets/15174041/12070499/55f010da-b046-11e5-9a65-60c06974318b.png)

**Comment by kaikreuzer** [comment]
I just tried to official openHAB_Runtime launch config from the latest master and all works fine with it.

**Comment by mickey4u** [comment]
Wow I installed mine this monday

**Comment by mickey4u** [comment]
Please what do suggest I do to fix it

**Comment by kaikreuzer** [comment]
I doubt that there has been anything changed since Monday.
Try following https://github.com/openhab/openhab2/blob/master/docs/sources/development/ide.md step by step.

**Comment by mickey4u** [comment]
I installed it again and it worked. Thanks
