### ISSUE TITLE
Errors (Console Logs when running a binding in the eclipse IDE)

### ISSUE THREAD

**Issue by mickey4u** [openhab/openhab2#592]
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.smarthome.model.item.runtime.internal.ItemRuntimeActivator

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

and alot of !Entry and !Message messages

**Comment by kaikreuzer** [comment]
I just tried to official openHAB_Runtime launch config from the latest master and all works fine with it.
