### ISSUE TITLE
Why does my project folder have a question mark as compared to the others ?

### ISSUE THREAD

**Issue by mickey4u** [openhab/openhab2#594]
![questionmark](https://cloud.githubusercontent.com/assets/15174041/12074347/8a274f0a-b11b-11e5-9871-a90466e0ec47.png)

**Comment by kaikreuzer** [comment]
Please don't use this issue tracker for such general questions. Rather use https://community.openhab.org/ instead.
For questions like this that are not related to openHAB at all, you might better simply use Google: http://stackoverflow.com/questions/4307086/why-does-eclipse-java-package-explorer-show-question-mark-on-some-classes
