### ISSUE TITLE
playerItem rendering in Classic UI

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab2#66]
Kai,
in order to fully test and integrate playerItems, we would need something to support it in the UI. I am no hero at doing UI's, but I can imagine a widget with 6 buttons to present play/stop and so forth?

**Comment by kgoderis** [comment]
Kai, in the above screenshot, did you use an additional "mapping=" to get the labels on the buttons? in my tests these are rendered as <  || > and >>, and I only have 4 buttons instead of 6 like you

**Comment by kaikreuzer** [comment]
You are right, I have actually changed this when preparing demos, because I noticed that it was rather unusable on a phone. With the new style, it fits nicely on the screen. I think it is much better. Would you agree?
