### ISSUE TITLE
IE not supported

### ISSUE THREAD

**Issue by wolter** [openhab/openhab2#73]
Hi, I am not sure if this is mentioned somewhere, but none of the UIs of the latest release does work correctly in Windows IE. Chrome does fine btw.

**Comment by kaikreuzer** [comment]
The newly developed Basic UI (https://github.com/eclipse/smarthome/blob/master/extensions/ui/org.eclipse.smarthome.ui.basic/README.md) has been designed to work on IE, so this issue should now be addressed.
