### ISSUE TITLE
DSC Alarm Binding

### ISSUE THREAD

**Issue by RSStephens** [openhab/openhab2#99]
I will start working on this binding the beginning of the new year.

**Comment by kaikreuzer** [comment]
Great to hear! I hope you mean this year because it has already started ;-)

**Comment by RSStephens** [comment]
lol! yes, this year.  I'm still in holiday mode :-)

**Comment by kaikreuzer** [comment]
Implemented and merged with https://github.com/openhab/openhab2/pull/324.

Thanks for the contribution!
